/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "../support/lpp-r18.4.0/37355-i40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-JER`
 */

#ifndef	_LPP_EPDU_Body_H_
#define	_LPP_EPDU_Body_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LPP_EPDU-Body */
typedef OCTET_STRING_t	 LPP_EPDU_Body_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_EPDU_Body;
asn_struct_free_f LPP_EPDU_Body_free;
asn_struct_print_f LPP_EPDU_Body_print;
asn_constr_check_f LPP_EPDU_Body_constraint;
per_type_decoder_f LPP_EPDU_Body_decode_uper;
per_type_encoder_f LPP_EPDU_Body_encode_uper;
per_type_decoder_f LPP_EPDU_Body_decode_aper;
per_type_encoder_f LPP_EPDU_Body_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_EPDU_Body_H_ */
#include <asn_internal.h>
