/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "../support/lpp-r18.4.0/37355-i40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-JER`
 */

#ifndef	_LPP_BT_ULA_GenericAntElement_r18_H_
#define	_LPP_BT_ULA_GenericAntElement_r18_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LPP_BT-ULA-GenericAntElement-r18 */
typedef struct LPP_BT_ULA_GenericAntElement_r18 {
	long	*deltaY_r18;	/* OPTIONAL */
	long	*deltaX_r18;	/* OPTIONAL */
	long	*deltaZ_r18;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_BT_ULA_GenericAntElement_r18_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_BT_ULA_GenericAntElement_r18;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_BT_ULA_GenericAntElement_r18_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_BT_ULA_GenericAntElement_r18_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_BT_ULA_GenericAntElement_r18_H_ */
#include <asn_internal.h>
