/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "../support/lpp-r18.4.0/37355-i40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-JER`
 */

#ifndef	_LPP_LocationInformationType_H_
#define	_LPP_LocationInformationType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_LocationInformationType {
	LPP_LocationInformationType_locationEstimateRequired	= 0,
	LPP_LocationInformationType_locationMeasurementsRequired	= 1,
	LPP_LocationInformationType_locationEstimatePreferred	= 2,
	LPP_LocationInformationType_locationMeasurementsPreferred	= 3,
	/*
	 * Enumeration is extensible
	 */
	LPP_LocationInformationType_locationEstimateAndMeasurementsRequired_r18	= 4
} e_LPP_LocationInformationType;

/* LPP_LocationInformationType */
typedef long	 LPP_LocationInformationType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LPP_LocationInformationType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LPP_LocationInformationType;
extern const asn_INTEGER_specifics_t asn_SPC_LPP_LocationInformationType_specs_1;
asn_struct_free_f LPP_LocationInformationType_free;
asn_struct_print_f LPP_LocationInformationType_print;
asn_constr_check_f LPP_LocationInformationType_constraint;
per_type_decoder_f LPP_LocationInformationType_decode_uper;
per_type_encoder_f LPP_LocationInformationType_encode_uper;
per_type_decoder_f LPP_LocationInformationType_decode_aper;
per_type_encoder_f LPP_LocationInformationType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_LocationInformationType_H_ */
#include <asn_internal.h>
