/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "../support/lpp-r18.4.0/37355-i40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-JER`
 */

#ifndef	_LPP_Ellipsoid_PointWithUncertaintyCircle_H_
#define	_LPP_Ellipsoid_PointWithUncertaintyCircle_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_Ellipsoid_PointWithUncertaintyCircle__latitudeSign {
	LPP_Ellipsoid_PointWithUncertaintyCircle__latitudeSign_north	= 0,
	LPP_Ellipsoid_PointWithUncertaintyCircle__latitudeSign_south	= 1
} e_LPP_Ellipsoid_PointWithUncertaintyCircle__latitudeSign;

/* LPP_Ellipsoid-PointWithUncertaintyCircle */
typedef struct LPP_Ellipsoid_PointWithUncertaintyCircle {
	long	 latitudeSign;
	long	 degreesLatitude;
	long	 degreesLongitude;
	long	 uncertainty;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_Ellipsoid_PointWithUncertaintyCircle_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_latitudeSign_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_Ellipsoid_PointWithUncertaintyCircle;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_Ellipsoid_PointWithUncertaintyCircle_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_Ellipsoid_PointWithUncertaintyCircle_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_Ellipsoid_PointWithUncertaintyCircle_H_ */
#include <asn_internal.h>
