/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "../support/lpp-r18.4.0/37355-i40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-JER`
 */

#ifndef	_LPP_HA_EllipsoidPointWithScalableUncertaintyEllipse_r16_H_
#define	_LPP_HA_EllipsoidPointWithScalableUncertaintyEllipse_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LPP_HA-EllipsoidPointWithScalableUncertaintyEllipse-r16 */
typedef struct LPP_HA_EllipsoidPointWithScalableUncertaintyEllipse_r16 {
	long	 degreesLatitude_r16;
	long	 degreesLongitude_r16;
	long	 uncertaintySemiMajor_r16;
	long	 uncertaintySemiMinor_r16;
	long	 orientationMajorAxis_r16;
	long	 confidence_r16;
	BOOLEAN_t	 ha_ExtendedUncertaintyRangeUsed_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_HA_EllipsoidPointWithScalableUncertaintyEllipse_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_HA_EllipsoidPointWithScalableUncertaintyEllipse_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_HA_EllipsoidPointWithScalableUncertaintyEllipse_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_HA_EllipsoidPointWithScalableUncertaintyEllipse_r16_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_HA_EllipsoidPointWithScalableUncertaintyEllipse_r16_H_ */
#include <asn_internal.h>
