/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "../support/lpp-r18.4.0/37355-i40.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-JER`
 */

#ifndef	_LPP_ReportingDuration_H_
#define	_LPP_ReportingDuration_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LPP_ReportingDuration */
typedef long	 LPP_ReportingDuration_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LPP_ReportingDuration_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LPP_ReportingDuration;
asn_struct_free_f LPP_ReportingDuration_free;
asn_struct_print_f LPP_ReportingDuration_print;
asn_constr_check_f LPP_ReportingDuration_constraint;
per_type_decoder_f LPP_ReportingDuration_decode_uper;
per_type_encoder_f LPP_ReportingDuration_encode_uper;
per_type_decoder_f LPP_ReportingDuration_decode_aper;
per_type_encoder_f LPP_ReportingDuration_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_ReportingDuration_H_ */
#include <asn_internal.h>
