# Copyright (C) 2019 by Sukchan Lee <acetcom@gmail.com>

# This file is part of Open5GS.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

libasn1c_lpp_sources = files('''
    LPP_A-GNSS-Error.c
LPP_A-GNSS-ProvideAssistanceData.c
LPP_A-GNSS-ProvideCapabilities.c
LPP_A-GNSS-ProvideLocationInformation.c
LPP_A-GNSS-RequestAssistanceData.c
LPP_A-GNSS-RequestCapabilities.c
LPP_A-GNSS-RequestLocationInformation.c
LPP_ARFCN-ValueEUTRA-r14.c
LPP_ARFCN-ValueEUTRA-v9a0.c
LPP_ARFCN-ValueEUTRA.c
LPP_ARFCN-ValueNR-r15.c
LPP_ARFCN-ValueUTRA.c
LPP_AUX-ReferenceStationID-Element-r15.c
LPP_AUX-ReferenceStationList-r15.c
LPP_Abort-r9-IEs.c
LPP_Abort.c
LPP_AccessTypes.c
LPP_Acknowledgement.c
LPP_Add-PRSconfigNeighbourElement-r14.c
LPP_AdditionalInformation.c
LPP_AdditionalPath-r14.c
LPP_AdditionalPathList-r14.c
LPP_AlmanacBDS-AlmanacSet-r12.c
LPP_AlmanacECEF-SBAS-AlmanacSet.c
LPP_AlmanacGLONASS-AlmanacSet.c
LPP_AlmanacKeplerianSet.c
LPP_AlmanacMidiAlmanacSet.c
LPP_AlmanacNAV-KeplerianSet.c
LPP_AlmanacNavIC-AlmanacSet-r16.c
LPP_AlmanacReducedKeplerianSet.c
LPP_AntennaDescription-r15.c
LPP_AntennaReferencePointUnc-r15.c
LPP_AreaID-CellList-r17.c
LPP_ArrayOfGridPoints-r18.c
LPP_AssistanceDataSupportList.c
LPP_Aux-ARP-Unc-r15.c
LPP_AuxiliaryStationElement-r15.c
LPP_AuxiliaryStationList-r15.c
LPP_BDS-ClockModel-r12.c
LPP_BDS-ClockModel2-r16.c
LPP_BDS-DifferentialCorrections-r12.c
LPP_BDS-DifferentialCorrectionsReq-r12.c
LPP_BDS-DifferentialCorrectionsSupport-r12.c
LPP_BDS-GridModelParameter-r12.c
LPP_BDS-GridModelReq-r12.c
LPP_BDS-GridModelSupport-r12.c
LPP_BDS-SgnTypeElement-r12.c
LPP_BDS-SgnTypeList-r12.c
LPP_BT-AntArrayConfig-r18.c
LPP_BT-AntElement-r18.c
LPP_BT-AntSwitchElement-r18.c
LPP_BT-AoA-Config-r18.c
LPP_BT-AoD-TransmConfig-r18.c
LPP_BT-BeaconInfo-r18.c
LPP_BT-BeaconInfoElement-r18.c
LPP_BT-Error-r13.c
LPP_BT-GenericArray-r18.c
LPP_BT-LocationServerErrorCauses-r13.c
LPP_BT-MeasurementElement-r13.c
LPP_BT-MeasurementElement-r18.c
LPP_BT-MeasurementInformation-r13.c
LPP_BT-MeasurementList-r13.c
LPP_BT-MeasurementList-r18.c
LPP_BT-ProvideAssistanceData-r18.c
LPP_BT-ProvideCapabilities-r13.c
LPP_BT-ProvideLocationInformation-r13.c
LPP_BT-RequestAssistanceData-r18.c
LPP_BT-RequestCapabilities-r13.c
LPP_BT-RequestLocationInformation-r13.c
LPP_BT-SuggestedAoA-Config-r18.c
LPP_BT-TargetDeviceErrorCauses-r13.c
LPP_BT-ULA-GenericAntElement-r18.c
LPP_BT-UniformCircularArray-r18.c
LPP_BT-UniformLinearArray-r18.c
LPP_BT-UniformRectangularArray-r18.c
LPP_BadSignalElement.c
LPP_BeamPowerElement-r17.c
LPP_CLOCK-IntegrityParameters-r17.c
LPP_CNAV-ClockModel.c
LPP_CarrierFreq-NB-r14.c
LPP_CarrierFreqOffsetNB-r14.c
LPP_CellGlobalIdEUTRA-AndUTRA.c
LPP_CellGlobalIdGERAN.c
LPP_CommonIEsAbort.c
LPP_CommonIEsError.c
LPP_CommonIEsProvideAssistanceData.c
LPP_CommonIEsProvideCapabilities.c
LPP_CommonIEsProvideLocationInformation.c
LPP_CommonIEsRequestAssistanceData.c
LPP_CommonIEsRequestCapabilities.c
LPP_CommonIEsRequestLocationInformation.c
LPP_DBDS-CorrectionElement-r12.c
LPP_DBDS-CorrectionList-r12.c
LPP_DGNSS-CorrectionsElement.c
LPP_DGNSS-SatList.c
LPP_DGNSS-SgnTypeElement.c
LPP_DGNSS-SgnTypeList.c
LPP_DL-AoD-MeasCapabilityPerBand-r16.c
LPP_DL-PRS-BeamInfoElement-r16.c
LPP_DL-PRS-BeamInfoResourceSet-r16.c
LPP_DL-PRS-BeamInfoSet-r16.c
LPP_DL-PRS-Configuration-ID-r17.c
LPP_DL-PRS-ID-Info-r16.c
LPP_DL-PRS-MeasurementWithRxFH-RRC-Connected-r18.c
LPP_DL-PRS-MutingOption1-r16.c
LPP_DL-PRS-MutingOption2-r16.c
LPP_DL-PRS-QCL-Info-r16.c
LPP_DL-PRS-QCL-InfoReq-r17.c
LPP_DL-PRS-QCL-InformationReqPerTRP-r17.c
LPP_DL-PRS-QCL-InformationReqTRPlist-r17.c
LPP_DL-PRS-QCL-ProcessingCapabilityPerBand-r16.c
LPP_DL-PRS-Resource-ARP-Element-r16.c
LPP_DL-PRS-ResourcePrioritySubset-r17.c
LPP_DL-PRS-ResourceSets-TRP-Element-r16.c
LPP_DL-PRS-ResourcesBandCombination-r16.c
LPP_DL-PRS-ResourcesBandCombinationList-r16.c
LPP_DL-PRS-ResourcesCapabilityPerBand-r16.c
LPP_DL-PRS-StartTime-and-Duration-r17.c
LPP_DL-PRS-TEG-InfoElement-r17.c
LPP_DL-PRS-TEG-InfoPerResourceSet-r17.c
LPP_DL-SelectedPRS-ResourceIndex-r16.c
LPP_DL-SelectedPRS-ResourceSetIndex-r16.c
LPP_DL-TDOA-MeasCapabilityPerBand-r17.c
LPP_Delta-Height-r16.c
LPP_Delta-Latitude-r16.c
LPP_Delta-Longitude-r16.c
LPP_DeltaTime-r15.c
LPP_Displacement-r15.c
LPP_DisplacementInfoList-r15.c
LPP_DisplacementInfoListElement-r15.c
LPP_DisplacementTimeStamp-r15.c
LPP_ECGI.c
LPP_ECID-Error.c
LPP_ECID-LocationServerErrorCauses.c
LPP_ECID-ProvideCapabilities.c
LPP_ECID-ProvideLocationInformation.c
LPP_ECID-RequestCapabilities.c
LPP_ECID-RequestLocationInformation.c
LPP_ECID-SignalMeasurementInformation.c
LPP_ECID-TargetDeviceErrorCauses.c
LPP_EPDU-Body.c
LPP_EPDU-ID.c
LPP_EPDU-Identifier.c
LPP_EPDU-Name.c
LPP_EPDU-Sequence.c
LPP_EPDU.c
LPP_EarlyFixReport-r12.c
LPP_ElevationElement-R17.c
LPP_Ellipsoid-Point.c
LPP_Ellipsoid-PointWithUncertaintyCircle.c
LPP_EllipsoidArc.c
LPP_EllipsoidPointWithAltitude.c
LPP_EllipsoidPointWithAltitudeAndUncertaintyEllipsoid.c
LPP_EllipsoidPointWithUncertaintyEllipse.c
LPP_Environment.c
LPP_EqualIntegerAmbiguityLevel-r16.c
LPP_Error-r9-IEs.c
LPP_Error.c
LPP_FKP-Gradients-Element-r15.c
LPP_FKP-Gradients-List-r15.c
LPP_FreqBandIndicatorNR-r16.c
LPP_GLO-RTK-BiasInformation-r15.c
LPP_GLO-RTK-BiasInformationReq-r15.c
LPP_GLO-RTK-BiasInformationSupport-r15.c
LPP_GLONASS-ClockModel.c
LPP_GNSS-AcquisitionAssistElement.c
LPP_GNSS-AcquisitionAssistList.c
LPP_GNSS-AcquisitionAssistance.c
LPP_GNSS-AcquisitionAssistanceReq.c
LPP_GNSS-AcquisitionAssistanceSupport.c
LPP_GNSS-Almanac.c
LPP_GNSS-AlmanacElement.c
LPP_GNSS-AlmanacList.c
LPP_GNSS-AlmanacReq.c
LPP_GNSS-AlmanacSupport.c
LPP_GNSS-AuxiliaryInformation.c
LPP_GNSS-AuxiliaryInformationReq.c
LPP_GNSS-AuxiliaryInformationSupport.c
LPP_GNSS-BadSignalList.c
LPP_GNSS-ClockModel.c
LPP_GNSS-CommonAssistData.c
LPP_GNSS-CommonAssistDataReq.c
LPP_GNSS-CommonAssistanceDataSupport.c
LPP_GNSS-DataBitAssistance.c
LPP_GNSS-DataBitAssistanceReq.c
LPP_GNSS-DataBitAssistanceSupport.c
LPP_GNSS-DataBitsReqSatElement.c
LPP_GNSS-DataBitsReqSatList.c
LPP_GNSS-DataBitsSatElement.c
LPP_GNSS-DataBitsSatList.c
LPP_GNSS-DataBitsSgnElement.c
LPP_GNSS-DataBitsSgnList.c
LPP_GNSS-DifferentialCorrections.c
LPP_GNSS-DifferentialCorrectionsReq.c
LPP_GNSS-DifferentialCorrectionsSupport.c
LPP_GNSS-EarthOrientationParameters.c
LPP_GNSS-EarthOrientationParametersReq.c
LPP_GNSS-EarthOrientationParametersSupport.c
LPP_GNSS-FrequencyID-r15.c
LPP_GNSS-GenericAssistData.c
LPP_GNSS-GenericAssistDataElement.c
LPP_GNSS-GenericAssistDataReq.c
LPP_GNSS-GenericAssistDataReqElement.c
LPP_GNSS-GenericAssistDataSupportElement.c
LPP_GNSS-GenericAssistanceDataSupport.c
LPP_GNSS-ID-BDS-SatElement-r16.c
LPP_GNSS-ID-BDS-r16.c
LPP_GNSS-ID-Bitmap.c
LPP_GNSS-ID-GLONASS-SatElement.c
LPP_GNSS-ID-GLONASS.c
LPP_GNSS-ID-GPS-SatElement.c
LPP_GNSS-ID-GPS.c
LPP_GNSS-ID.c
LPP_GNSS-Integrity-ServiceAlert-r17.c
LPP_GNSS-Integrity-ServiceAlertReq-r17.c
LPP_GNSS-Integrity-ServiceAlertSupport-r17.c
LPP_GNSS-Integrity-ServiceParameters-r17.c
LPP_GNSS-Integrity-ServiceParametersReq-r17.c
LPP_GNSS-Integrity-ServiceParametersSupport-r17.c
LPP_GNSS-IonosphericModel.c
LPP_GNSS-IonosphericModelReq.c
LPP_GNSS-IonosphericModelSupport.c
LPP_GNSS-LOS-InfoElement-r18.c
LPP_GNSS-LOS-InfoList-r18.c
LPP_GNSS-LOS-NLOS-GridPoints-r18.c
LPP_GNSS-LOS-NLOS-GriddedIndications-r18.c
LPP_GNSS-LOS-NLOS-GriddedIndicationsReq-r18.c
LPP_GNSS-LOS-NLOS-GriddedIndicationsSupport-r18.c
LPP_GNSS-Link-Combinations-r15.c
LPP_GNSS-Link-CombinationsList-r15.c
LPP_GNSS-LocationInformation.c
LPP_GNSS-LocationServerErrorCauses.c
LPP_GNSS-MeasurementForOneGNSS.c
LPP_GNSS-MeasurementList.c
LPP_GNSS-NavListInfo-r15.c
LPP_GNSS-NavModelSatelliteElement.c
LPP_GNSS-NavModelSatelliteList.c
LPP_GNSS-NavigationModel.c
LPP_GNSS-NavigationModelReq.c
LPP_GNSS-NavigationModelSupport.c
LPP_GNSS-NetworkID-r15.c
LPP_GNSS-ObservationList-r15.c
LPP_GNSS-OrbitModel.c
LPP_GNSS-PeriodicAssistData-r15.c
LPP_GNSS-PeriodicAssistDataReq-r15.c
LPP_GNSS-PeriodicControlParam-r15.c
LPP_GNSS-PositioningInstructions.c
LPP_GNSS-RTK-AuxiliaryStationData-r15.c
LPP_GNSS-RTK-AuxiliaryStationDataReq-r15.c
LPP_GNSS-RTK-AuxiliaryStationDataSupport-r15.c
LPP_GNSS-RTK-CommonObservationInfo-r15.c
LPP_GNSS-RTK-FKP-Gradients-r15.c
LPP_GNSS-RTK-FKP-GradientsReq-r15.c
LPP_GNSS-RTK-FKP-GradientsSupport-r15.c
LPP_GNSS-RTK-MAC-CorrectionDifferences-r15.c
LPP_GNSS-RTK-MAC-CorrectionDifferencesReq-r15.c
LPP_GNSS-RTK-MAC-CorrectionDifferencesSupport-r15.c
LPP_GNSS-RTK-Observations-r15.c
LPP_GNSS-RTK-ObservationsReq-r15.c
LPP_GNSS-RTK-ObservationsSupport-r15.c
LPP_GNSS-RTK-ReferenceStationInfo-r15.c
LPP_GNSS-RTK-ReferenceStationInfoReq-r15.c
LPP_GNSS-RTK-ReferenceStationInfoSupport-r15.c
LPP_GNSS-RTK-Residuals-r15.c
LPP_GNSS-RTK-ResidualsReq-r15.c
LPP_GNSS-RTK-ResidualsSupport-r15.c
LPP_GNSS-RTK-SatelliteDataElement-r15.c
LPP_GNSS-RTK-SatelliteSignalDataElement-r15.c
LPP_GNSS-RTK-SatelliteSignalDataList-r15.c
LPP_GNSS-RealTimeIntegrity.c
LPP_GNSS-RealTimeIntegrityReq.c
LPP_GNSS-RealTimeIntegritySupport.c
LPP_GNSS-ReferenceLocation.c
LPP_GNSS-ReferenceLocationReq.c
LPP_GNSS-ReferenceLocationSupport.c
LPP_GNSS-ReferenceStationID-r15.c
LPP_GNSS-ReferenceTime.c
LPP_GNSS-ReferenceTimeForOneCell.c
LPP_GNSS-ReferenceTimeReq.c
LPP_GNSS-ReferenceTimeSupport.c
LPP_GNSS-SSR-ArrayOfCorrectionPoints-r16.c
LPP_GNSS-SSR-ClockCorrections-r15.c
LPP_GNSS-SSR-ClockCorrectionsReq-r15.c
LPP_GNSS-SSR-ClockCorrectionsSet2-r17.c
LPP_GNSS-SSR-ClockCorrectionsSet2Req-r17.c
LPP_GNSS-SSR-ClockCorrectionsSet2Support-r17.c
LPP_GNSS-SSR-ClockCorrectionsSupport-r15.c
LPP_GNSS-SSR-CodeBias-r15.c
LPP_GNSS-SSR-CodeBiasReq-r15.c
LPP_GNSS-SSR-CodeBiasSupport-r15.c
LPP_GNSS-SSR-CorrectionPoints-r16.c
LPP_GNSS-SSR-CorrectionPointsReq-r16.c
LPP_GNSS-SSR-GriddedCorrection-r16.c
LPP_GNSS-SSR-GriddedCorrectionReq-r16.c
LPP_GNSS-SSR-GriddedCorrectionSupport-r16.c
LPP_GNSS-SSR-IOD-Update-r18.c
LPP_GNSS-SSR-IOD-UpdateReq-r18.c
LPP_GNSS-SSR-IOD-UpdateSupport-r18.c
LPP_GNSS-SSR-ListOfCorrectionPoints-r16.c
LPP_GNSS-SSR-OrbitCorrections-r15.c
LPP_GNSS-SSR-OrbitCorrectionsReq-r15.c
LPP_GNSS-SSR-OrbitCorrectionsSet2-r17.c
LPP_GNSS-SSR-OrbitCorrectionsSet2Req-r17.c
LPP_GNSS-SSR-OrbitCorrectionsSet2Support-r17.c
LPP_GNSS-SSR-OrbitCorrectionsSupport-r15.c
LPP_GNSS-SSR-PhaseBias-r16.c
LPP_GNSS-SSR-PhaseBiasReq-r16.c
LPP_GNSS-SSR-PhaseBiasSupport-r16.c
LPP_GNSS-SSR-STEC-Correction-r16.c
LPP_GNSS-SSR-STEC-CorrectionReq-r16.c
LPP_GNSS-SSR-STEC-CorrectionSupport-r16.c
LPP_GNSS-SSR-SatellitePCVResiduals-r18.c
LPP_GNSS-SSR-SatellitePCVResidualsReq-r18.c
LPP_GNSS-SSR-SatellitePCVResidualsSupport-r18.c
LPP_GNSS-SSR-URA-Req-r16.c
LPP_GNSS-SSR-URA-Set2-r17.c
LPP_GNSS-SSR-URA-Set2Req-r17.c
LPP_GNSS-SSR-URA-Set2Support-r17.c
LPP_GNSS-SSR-URA-Support-r16.c
LPP_GNSS-SSR-URA-r16.c
LPP_GNSS-SatMeasElement.c
LPP_GNSS-SatMeasList.c
LPP_GNSS-SgnMeasElement.c
LPP_GNSS-SgnMeasList.c
LPP_GNSS-SignalID.c
LPP_GNSS-SignalIDs.c
LPP_GNSS-SignalMeasurementInformation.c
LPP_GNSS-SubNetworkID-r15.c
LPP_GNSS-SupportElement.c
LPP_GNSS-SupportList.c
LPP_GNSS-SystemTime.c
LPP_GNSS-TargetDeviceErrorCauses.c
LPP_GNSS-TimeModelElement.c
LPP_GNSS-TimeModelElementReq.c
LPP_GNSS-TimeModelList.c
LPP_GNSS-TimeModelListReq.c
LPP_GNSS-TimeModelListSupport.c
LPP_GNSS-UTC-Model.c
LPP_GNSS-UTC-ModelReq.c
LPP_GNSS-UTC-ModelSupport.c
LPP_GPS-TOW-Assist.c
LPP_GPS-TOW-AssistElement.c
LPP_Geometric-Ionospheric-Corrections-Differences-Element-r15.c
LPP_Geometric-Ionospheric-Corrections-Differences-r15.c
LPP_GridElement-r16.c
LPP_GridElement-r18.c
LPP_GridIonElement-r12.c
LPP_GridIonList-r12.c
LPP_GridList-r16.c
LPP_GridList-r18.c
LPP_HA-EllipsoidPointWithAltitudeAndScalableUncertaintyEllipsoid-r16.c
LPP_HA-EllipsoidPointWithScalableUncertaintyEllipse-r16.c
LPP_HA-GNSS-Metrics-r17.c
LPP_HighAccuracyEllipsoidPointWithAltitudeAndUncertaintyEllipsoid-r15.c
LPP_HighAccuracyEllipsoidPointWithUncertaintyEllipse-r15.c
LPP_HorizontalAccuracy.c
LPP_HorizontalAccuracyExt-r15.c
LPP_HorizontalVelocity.c
LPP_HorizontalVelocityWithUncertainty.c
LPP_HorizontalWithVerticalVelocity.c
LPP_HorizontalWithVerticalVelocityAndUncertainty.c
LPP_Initiator.c
LPP_IntegrityInfo-r17.c
LPP_KlobucharModel2Parameter-r16.c
LPP_KlobucharModelParameter.c
LPP_LCS-GCS-TranslationParameter-r16.c
LPP_LOS-NLOS-Indicator-r17.c
LPP_LOS-NLOS-IndicatorGranularity1-r17.c
LPP_LOS-NLOS-IndicatorGranularity2-r17.c
LPP_LOS-NLOS-IndicatorType1-r17.c
LPP_LOS-NLOS-IndicatorType2-r17.c
LPP_LPP-Message.c
LPP_LPP-MessageBody.c
LPP_LPP-TransactionID.c
LPP_Local2dPointWithUncertaintyEllipse-r18.c
LPP_Local3dPointWithUncertaintyEllipsoid-r18.c
LPP_LocalOrigin-r18.c
LPP_LocationCoordinateTypes.c
LPP_LocationCoordinates.c
LPP_LocationDataLCI-r14.c
LPP_LocationError.c
LPP_LocationFailureCause.c
LPP_LocationInformationType.c
LPP_LocationSource-r13.c
LPP_LocationUncertainty-r16.c
LPP_MBS-AcquisitionAssistance-r14.c
LPP_MBS-AlmanacAssistance-r14.c
LPP_MBS-AssistanceDataElement-r14.c
LPP_MBS-AssistanceDataList-r14.c
LPP_MBS-AssistanceDataSupportList-r14.c
LPP_MBS-BeaconMeasElement-r13.c
LPP_MBS-BeaconMeasList-r13.c
LPP_MeasQuantityResults-r16.c
LPP_MeasuredResultsElement.c
LPP_MeasuredResultsList.c
LPP_MeasurementReferenceTime.c
LPP_MessageSizeLimitNB-r14.c
LPP_MotionTimeSource-r15.c
LPP_Multi-RTT-MeasCapabilityPerBand-r17.c
LPP_NAV-ClockModel.c
LPP_NCGI-r15.c
LPP_NPRS-Info-r14.c
LPP_NR-AdditionalPath-r16.c
LPP_NR-AdditionalPathList-r16.c
LPP_NR-AdditionalPathListExt-r17.c
LPP_NR-AggregatedDL-PRS-ResourceInfo-Element-r18.c
LPP_NR-Cell-IDs-r17.c
LPP_NR-DL-AoD-AdditionalMeasurementElement-r16.c
LPP_NR-DL-AoD-AdditionalMeasurementElement-r17.c
LPP_NR-DL-AoD-AdditionalMeasurements-r16.c
LPP_NR-DL-AoD-AdditionalMeasurementsExt-r17.c
LPP_NR-DL-AoD-Error-r16.c
LPP_NR-DL-AoD-LocationInformation-r16.c
LPP_NR-DL-AoD-LocationServerErrorCauses-r16.c
LPP_NR-DL-AoD-MeasElement-r16.c
LPP_NR-DL-AoD-MeasList-r16.c
LPP_NR-DL-AoD-MeasurementCapability-r16.c
LPP_NR-DL-AoD-ProvideAssistanceData-r16.c
LPP_NR-DL-AoD-ProvideCapabilities-r16.c
LPP_NR-DL-AoD-ProvideLocationInformation-r16.c
LPP_NR-DL-AoD-ReportConfig-r16.c
LPP_NR-DL-AoD-RequestAssistanceData-r16.c
LPP_NR-DL-AoD-RequestCapabilities-r16.c
LPP_NR-DL-AoD-RequestLocationInformation-r16.c
LPP_NR-DL-AoD-SignalMeasurementInformation-r16.c
LPP_NR-DL-AoD-TargetDeviceErrorCauses-r16.c
LPP_NR-DL-PRS-AggregationElement-r18.c
LPP_NR-DL-PRS-AggregationInfo-r18.c
LPP_NR-DL-PRS-AssistanceData-r16.c
LPP_NR-DL-PRS-AssistanceDataPerFreq-r16.c
LPP_NR-DL-PRS-AssistanceDataPerTRP-r16.c
LPP_NR-DL-PRS-BeamInfo-r16.c
LPP_NR-DL-PRS-BeamInfoPerFreqLayer-r16.c
LPP_NR-DL-PRS-BeamInfoPerTRP-r16.c
LPP_NR-DL-PRS-ExpectedAoD-or-AoA-r17.c
LPP_NR-DL-PRS-ExpectedLOS-NLOS-Assistance-r17.c
LPP_NR-DL-PRS-ExpectedLOS-NLOS-AssistancePerFreqLayer-r17.c
LPP_NR-DL-PRS-ExpectedLOS-NLOS-AssistancePerResource-r17.c
LPP_NR-DL-PRS-ExpectedLOS-NLOS-AssistancePerTRP-r17.c
LPP_NR-DL-PRS-Info-r16.c
LPP_NR-DL-PRS-MeasurementTimeWindowsConfig-r18.c
LPP_NR-DL-PRS-MeasurementTimeWindowsConfigElement-r18.c
LPP_NR-DL-PRS-Periodicity-and-ResourceSetSlotOffset-r16.c
LPP_NR-DL-PRS-PositioningFrequencyLayer-r16.c
LPP_NR-DL-PRS-ProcessingCapability-r16.c
LPP_NR-DL-PRS-QCL-ProcessingCapability-r16.c
LPP_NR-DL-PRS-Resource-r16.c
LPP_NR-DL-PRS-ResourceID-r16.c
LPP_NR-DL-PRS-ResourceSet-r16.c
LPP_NR-DL-PRS-ResourceSetID-r16.c
LPP_NR-DL-PRS-ResourcesCapability-r16.c
LPP_NR-DL-PRS-SFN0-Offset-r16.c
LPP_NR-DL-PRS-TRP-TEG-Info-r17.c
LPP_NR-DL-PRS-TRP-TEG-InfoPerFreqLayer-r17.c
LPP_NR-DL-PRS-TRP-TEG-InfoPerTRP-r17.c
LPP_NR-DL-PRSResourcePriorityItem-r17.c
LPP_NR-DL-TDOA-AdditionalMeasurementElement-r16.c
LPP_NR-DL-TDOA-AdditionalMeasurements-r16.c
LPP_NR-DL-TDOA-AdditionalMeasurementsExt-r17.c
LPP_NR-DL-TDOA-Error-r16.c
LPP_NR-DL-TDOA-LocationInformation-r16.c
LPP_NR-DL-TDOA-LocationServerErrorCauses-r16.c
LPP_NR-DL-TDOA-MeasElement-r16.c
LPP_NR-DL-TDOA-MeasList-r16.c
LPP_NR-DL-TDOA-MeasurementCapability-r16.c
LPP_NR-DL-TDOA-ProvideAssistanceData-r16.c
LPP_NR-DL-TDOA-ProvideCapabilities-r16.c
LPP_NR-DL-TDOA-ProvideLocationInformation-r16.c
LPP_NR-DL-TDOA-ReportConfig-r16.c
LPP_NR-DL-TDOA-RequestAssistanceData-r16.c
LPP_NR-DL-TDOA-RequestCapabilities-r16.c
LPP_NR-DL-TDOA-RequestLocationInformation-r16.c
LPP_NR-DL-TDOA-SignalMeasurementInformation-r16.c
LPP_NR-DL-TDOA-TargetDeviceErrorCauses-r16.c
LPP_NR-ECID-Error-r16.c
LPP_NR-ECID-LocationServerErrorCauses-r16.c
LPP_NR-ECID-ProvideCapabilities-r16.c
LPP_NR-ECID-ProvideLocationInformation-r16.c
LPP_NR-ECID-RequestCapabilities-r16.c
LPP_NR-ECID-RequestLocationInformation-r16.c
LPP_NR-ECID-SignalMeasurementInformation-r16.c
LPP_NR-ECID-TargetDeviceErrorCauses-r16.c
LPP_NR-IntegrityBeamInfoBounds-r18.c
LPP_NR-IntegrityBeamPowerBounds-r18.c
LPP_NR-IntegrityLocationBounds-r18.c
LPP_NR-IntegrityParametersDL-PRS-BeamInfo-r18.c
LPP_NR-IntegrityParametersRTD-Info-r18.c
LPP_NR-IntegrityParametersTRP-BeamAntennaInfo-r18.c
LPP_NR-IntegrityParametersTRP-LocationInfo-r18.c
LPP_NR-IntegrityRTD-InfoBounds-r18.c
LPP_NR-IntegrityRiskParameters-r18.c
LPP_NR-IntegrityServiceAlert-r18.c
LPP_NR-IntegrityServiceParameters-r18.c
LPP_NR-MeasuredResultsElement-r16.c
LPP_NR-MeasuredResultsList-r16.c
LPP_NR-Multi-RTT-AdditionalMeasurementElement-r16.c
LPP_NR-Multi-RTT-AdditionalMeasurements-r16.c
LPP_NR-Multi-RTT-AdditionalMeasurementsExt-r17.c
LPP_NR-Multi-RTT-Error-r16.c
LPP_NR-Multi-RTT-LocationServerErrorCauses-r16.c
LPP_NR-Multi-RTT-MeasElement-r16.c
LPP_NR-Multi-RTT-MeasList-r16.c
LPP_NR-Multi-RTT-MeasurementCapability-r16.c
LPP_NR-Multi-RTT-ProvideAssistanceData-r16.c
LPP_NR-Multi-RTT-ProvideCapabilities-r16.c
LPP_NR-Multi-RTT-ProvideLocationInformation-r16.c
LPP_NR-Multi-RTT-ReportConfig-r16.c
LPP_NR-Multi-RTT-RequestAssistanceData-r16.c
LPP_NR-Multi-RTT-RequestCapabilities-r16.c
LPP_NR-Multi-RTT-RequestLocationInformation-r16.c
LPP_NR-Multi-RTT-SignalMeasurementInformation-r16.c
LPP_NR-Multi-RTT-TargetDeviceErrorCauses-r16.c
LPP_NR-MutingPattern-r16.c
LPP_NR-NTN-UE-RxTxMeasurements-r18.c
LPP_NR-On-Demand-DL-PRS-Configurations-Selected-IndexList-r17.c
LPP_NR-On-Demand-DL-PRS-Configurations-r17.c
LPP_NR-On-Demand-DL-PRS-Information-r17.c
LPP_NR-On-Demand-DL-PRS-PerFreqLayer-r17.c
LPP_NR-On-Demand-DL-PRS-Request-r17.c
LPP_NR-On-Demand-DL-PRS-Support-r17.c
LPP_NR-OnDemandDL-PRS-AggregationReqElement-r18.c
LPP_NR-PRU-DL-Info-r18.c
LPP_NR-PRU-RSCP-AdditionalMeasurementElement-r18.c
LPP_NR-PRU-RSCP-AdditionalMeasurements-r18.c
LPP_NR-PRU-RSCP-MeasElement-r18.c
LPP_NR-PRU-RSCP-MeasurementInformation-r18.c
LPP_NR-PeriodicAssistData-r18.c
LPP_NR-PeriodicAssistDataReq-r18.c
LPP_NR-PeriodicControlParam-r18.c
LPP_NR-PhaseQuality-r18.c
LPP_NR-PhysCellID-r16.c
LPP_NR-PositionCalculationAssistance-r16.c
LPP_NR-RSCP-AdditionalMeasurements-r18.c
LPP_NR-RSCPD-AdditionalMeasurementSamplesElement-r18.c
LPP_NR-RTD-Info-r16.c
LPP_NR-SRS-TxTEG-Element-r17.c
LPP_NR-SSB-Config-r16.c
LPP_NR-SelectedDL-PRS-IndexList-r16.c
LPP_NR-SelectedDL-PRS-IndexPerTRP-r16.c
LPP_NR-SelectedDL-PRS-IndexPerTRP-r18.c
LPP_NR-SelectedDL-PRS-PerFreq-r16.c
LPP_NR-TRP-BeamAntennaAngles-r17.c
LPP_NR-TRP-BeamAntennaInfo-r17.c
LPP_NR-TRP-BeamAntennaInfoAzimuthElevation-r17.c
LPP_NR-TRP-BeamAntennaInfoPerFreqLayer-r17.c
LPP_NR-TRP-BeamAntennaInfoPerTRP-r17.c
LPP_NR-TRP-IntegrityServiceAlertElement-r18.c
LPP_NR-TRP-IntegrityServiceAlertPerFreqLayer-r18.c
LPP_NR-TRP-LocationInfo-r16.c
LPP_NR-TRP-LocationInfoPerFreqLayer-r16.c
LPP_NR-TimeStamp-r16.c
LPP_NR-TimingQuality-r16.c
LPP_NR-UE-RxTx-TEG-Info-r17.c
LPP_NR-UE-TEG-Capability-r17.c
LPP_NR-UE-TEG-ID-CapabilityPerBand-r17.c
LPP_NR-UL-ProvideCapabilities-r16.c
LPP_NR-UL-RequestCapabilities-r16.c
LPP_NR-UL-SRS-Capability-r16.c
LPP_NR-linkedDL-PRS-ResourceSetID-PRS-AggregationList-r18.c
LPP_NavIC-CDC-r16.c
LPP_NavIC-ClockModel-r16.c
LPP_NavIC-CorrectionElementAutoNav-r16.c
LPP_NavIC-CorrectionListAutoNav-r16.c
LPP_NavIC-DifferentialCorrections-r16.c
LPP_NavIC-DifferentialCorrectionsReq-r16.c
LPP_NavIC-DifferentialCorrectionsSupport-r16.c
LPP_NavIC-EDC-r16.c
LPP_NavIC-GridModelParameter-r16.c
LPP_NavIC-GridModelReq-r16.c
LPP_NavIC-GridModelSupport-r16.c
LPP_NavModel-BDS-KeplerianSet-r12.c
LPP_NavModel-BDS-KeplerianSet2-r16.c
LPP_NavModel-GLONASS-ECEF.c
LPP_NavModel-NavIC-KeplerianSet-r16.c
LPP_NavModel-SBAS-ECEF.c
LPP_NavModelCNAV-KeplerianSet.c
LPP_NavModelKeplerianSet.c
LPP_NavModelNAV-KeplerianSet.c
LPP_NeQuickModelParameter.c
LPP_NeighbourMeasurementElement-NB-r14.c
LPP_NeighbourMeasurementElement.c
LPP_NeighbourMeasurementList-NB-r14.c
LPP_NeighbourMeasurementList.c
LPP_NetworkTime.c
LPP_OLPC-SRS-Pos-r16.c
LPP_ORBIT-IntegrityParameters-r17.c
LPP_OTDOA-Error.c
LPP_OTDOA-LocationServerErrorCauses.c
LPP_OTDOA-MeasQuality.c
LPP_OTDOA-NeighbourCellInfoElement.c
LPP_OTDOA-NeighbourCellInfoList.c
LPP_OTDOA-NeighbourCellInfoListNB-r14.c
LPP_OTDOA-NeighbourCellInfoNB-r14.c
LPP_OTDOA-NeighbourFreqInfo.c
LPP_OTDOA-ProvideAssistanceData.c
LPP_OTDOA-ProvideCapabilities.c
LPP_OTDOA-ProvideLocationInformation.c
LPP_OTDOA-ReferenceCellInfo.c
LPP_OTDOA-ReferenceCellInfoNB-r14.c
LPP_OTDOA-RequestAssistanceData.c
LPP_OTDOA-RequestCapabilities.c
LPP_OTDOA-RequestLocationInformation.c
LPP_OTDOA-SignalMeasurementInformation-NB-r14.c
LPP_OTDOA-SignalMeasurementInformation.c
LPP_OTDOA-TargetDeviceErrorCauses.c
LPP_On-Demand-DL-PRS-Configuration-r17.c
LPP_OnDemandDL-PRS-AggregationInfo-r18.c
LPP_PRS-BWA-ThreeContiguousIntrabandInMG-r18.c
LPP_PRS-BWA-TwoContiguousIntrabandInMG-r18.c
LPP_PRS-Info-NB-r14.c
LPP_PRS-Info.c
LPP_PRS-ProcessingCapabilityOutsideMGinPPWperType-r17.c
LPP_PRS-ProcessingCapabilityPerBand-r16.c
LPP_PeriodicAssistanceDataControlParameters-r15.c
LPP_PeriodicReportingIntervalMsSupport-r18.c
LPP_PeriodicReportingIntervalMsSupportPerMode-r18.c
LPP_PeriodicSessionID-r15.c
LPP_PeriodicalReportingCriteria.c
LPP_PeriodicalReportingCriteriaExt-r18.c
LPP_PhysicalReferenceStationInfo-r15.c
LPP_Polygon.c
LPP_PolygonPoints.c
LPP_PosSRS-BWA-IndependentCA-RRC-Connected-r18.c
LPP_PosSRS-BWA-RRC-Connected-r18.c
LPP_PosSRS-BWA-RRC-Inactive-r18.c
LPP_PosSRS-RRC-Inactive-InInitialUL-BWP-r17.c
LPP_PosSRS-RRC-Inactive-OutsideInitialUL-BWP-r17.c
LPP_PosSRS-SP-RRC-Inactive-InInitialUL-BWP-r17.c
LPP_PosSRS-TxFrequencyHoppingRRC-Connected-r18.c
LPP_PosSRS-TxFrequencyHoppingRRC-Inactive-r18.c
LPP_PositioningModes.c
LPP_PressureValidityArea-v1520.c
LPP_PressureValidityPeriod-v1520.c
LPP_ProvideAssistanceData-r9-IEs.c
LPP_ProvideAssistanceData.c
LPP_ProvideCapabilities-r9-IEs.c
LPP_ProvideCapabilities.c
LPP_ProvideLocationInformation-r9-IEs.c
LPP_ProvideLocationInformation.c
LPP_QoS.c
LPP_RAC-OrbitalErrorComponents-r17.c
LPP_RTD-InfoElement-r16.c
LPP_RTD-InfoList-r16.c
LPP_RTD-InfoListPerFreqLayer-r16.c
LPP_RTK-CorrectionDifferencesElement-r15.c
LPP_RTK-CorrectionDifferencesList-r15.c
LPP_RTK-Residuals-Element-r15.c
LPP_RTK-Residuals-List-r15.c
LPP_ReferencePoint-r16.c
LPP_ReferenceStationList-r16.c
LPP_ReferenceTRP-RTD-Info-r16.c
LPP_RegionIgpElement-r16.c
LPP_RegionIgpList-r16.c
LPP_RelativeCartesianLocation-r18.c
LPP_RelativeLocation-r16.c
LPP_RelativeLocationElement-r16.c
LPP_ReportingDuration.c
LPP_ReqNavListInfo.c
LPP_RequestAssistanceData-r9-IEs.c
LPP_RequestAssistanceData.c
LPP_RequestCapabilities-r9-IEs.c
LPP_RequestCapabilities.c
LPP_RequestLocationInformation-r9-IEs.c
LPP_RequestLocationInformation.c
LPP_ResponseTime.c
LPP_ResponseTimeNB-r14.c
LPP_ResultsPerCSI-RS-Index-r16.c
LPP_ResultsPerCSI-RS-IndexList-r16.c
LPP_ResultsPerSSB-Index-r16.c
LPP_ResultsPerSSB-IndexList-r16.c
LPP_RxTxTEG-TimingErrorMargin-r17.c
LPP_SBAS-ClockModel.c
LPP_SBAS-ID.c
LPP_SBAS-IDs.c
LPP_SFN-r15.c
LPP_SRS-CapabilityPerBand-r16.c
LPP_SRS-PosResourcesPerBand-r16.c
LPP_SSR-ClockCorrectionList-r15.c
LPP_SSR-ClockCorrectionSatelliteElement-r15.c
LPP_SSR-CodeBiasSatElement-r15.c
LPP_SSR-CodeBiasSatList-r15.c
LPP_SSR-CodeBiasSignalElement-r15.c
LPP_SSR-CodeBiasSignalList-r15.c
LPP_SSR-GriddedCorrectionIntegrityParameters-r17.c
LPP_SSR-IntegrityClockBounds-r17.c
LPP_SSR-IntegrityCodeBiasBounds-r17.c
LPP_SSR-IntegrityOrbitBounds-r17.c
LPP_SSR-IntegrityPhaseBiasBounds-r17.c
LPP_SSR-OrbitCorrectionList-r15.c
LPP_SSR-OrbitCorrectionSatelliteElement-r15.c
LPP_SSR-PhaseBiasSatElement-r16.c
LPP_SSR-PhaseBiasSatList-r16.c
LPP_SSR-PhaseBiasSignalElement-r16.c
LPP_SSR-PhaseBiasSignalList-r16.c
LPP_SSR-PhaseCenterVariationList-r18.c
LPP_SSR-SatellitePCV-Element-r18.c
LPP_SSR-SatellitePCV-FrequencyElement-r18.c
LPP_SSR-SatellitePCV-FrequencyList-r18.c
LPP_SSR-SatellitePCV-List-r18.c
LPP_SSR-URA-SatElement-r16.c
LPP_SSR-URA-SatList-r16.c
LPP_STEC-IntegrityErrorBounds-r17.c
LPP_STEC-IntegrityParameters-r17.c
LPP_STEC-ResidualSatElement-r16.c
LPP_STEC-ResidualSatList-r16.c
LPP_STEC-SatElement-r16.c
LPP_STEC-SatList-r16.c
LPP_SV-ID.c
LPP_SatListElement-r15.c
LPP_SatListRelatedDataElement.c
LPP_SatListRelatedDataList.c
LPP_ScheduledLocationTime-r17.c
LPP_ScheduledLocationTimeSupport-r17.c
LPP_ScheduledLocationTimeSupportPerMode-r17.c
LPP_SegmentationInfo-r14.c
LPP_Sensor-AssistanceDataList-r14.c
LPP_Sensor-AssistanceDataSupportList-r14.c
LPP_Sensor-Error-r13.c
LPP_Sensor-LocationServerErrorCauses-r13.c
LPP_Sensor-MeasurementInformation-r13.c
LPP_Sensor-MotionInformation-r15.c
LPP_Sensor-ProvideAssistanceData-r14.c
LPP_Sensor-ProvideCapabilities-r13.c
LPP_Sensor-ProvideLocationInformation-r13.c
LPP_Sensor-RequestAssistanceData-r14.c
LPP_Sensor-RequestCapabilities-r13.c
LPP_Sensor-RequestLocationInformation-r13.c
LPP_Sensor-TargetDeviceErrorCauses-r13.c
LPP_SequenceNumber.c
LPP_SpatialDelta-r18.c
LPP_SpatialRelationsSRS-Pos-r16.c
LPP_StandardClockModelElement.c
LPP_StandardClockModelList.c
LPP_StoredNavListInfo.c
LPP_SupportedBandEUTRA-v9a0.c
LPP_SupportedBandEUTRA.c
LPP_SupportedChannels-11a-r14.c
LPP_SupportedChannels-11bg-r14.c
LPP_TBS-AssistanceDataList-r14.c
LPP_TBS-Error-r13.c
LPP_TBS-LocationServerErrorCauses-r13.c
LPP_TBS-MeasurementInformation-r13.c
LPP_TBS-ProvideAssistanceData-r14.c
LPP_TBS-ProvideCapabilities-r13.c
LPP_TBS-ProvideLocationInformation-r13.c
LPP_TBS-RequestAssistanceData-r14.c
LPP_TBS-RequestCapabilities-r13.c
LPP_TBS-RequestLocationInformation-r13.c
LPP_TBS-TargetDeviceErrorCauses-r13.c
LPP_TDD-Config-v1520.c
LPP_TEG-TimingErrorMargin-r17.c
LPP_TRP-LocationInfoElement-r16.c
LPP_TargetIntegrityRisk-r17.c
LPP_TransactionNumber.c
LPP_TriggeredReportingCriteria.c
LPP_TropoDelayIntegrityErrorBounds-r17.c
LPP_TropospericDelayCorrection-r16.c
LPP_UTC-ModelSet1.c
LPP_UTC-ModelSet2.c
LPP_UTC-ModelSet3.c
LPP_UTC-ModelSet4.c
LPP_UTC-ModelSet5-r12.c
LPP_UTC-Time-r15.c
LPP_UpdateCapabilities-r15.c
LPP_Velocity.c
LPP_VelocityTypes.c
LPP_VerticalAccuracy.c
LPP_VerticalAccuracyExt-r15.c
LPP_VerticalGridPoints-r18.c
LPP_WLAN-AP-Data-r14.c
LPP_WLAN-AP-Identifier-r13.c
LPP_WLAN-AP-Location-r14.c
LPP_WLAN-DataSet-r14.c
LPP_WLAN-Error-r13.c
LPP_WLAN-LocationServerErrorCauses-r13.c
LPP_WLAN-MeasurementElement-r13.c
LPP_WLAN-MeasurementInformation-r13.c
LPP_WLAN-MeasurementList-r13.c
LPP_WLAN-ProvideAssistanceData-r14.c
LPP_WLAN-ProvideCapabilities-r13.c
LPP_WLAN-ProvideLocationInformation-r13.c
LPP_WLAN-RTT-r13.c
LPP_WLAN-RequestAssistanceData-r14.c
LPP_WLAN-RequestCapabilities-r13.c
LPP_WLAN-RequestLocationInformation-r13.c
LPP_WLAN-TargetDeviceErrorCauses-r13.c
LPP_X-Value-r18.c
LPP_Y-Value-r18.c
LPP_Z-Value-r18.c
'''.split())

libasn1c_lpp_inc = include_directories('.')

libasn1c_lpp = library('ogsasn1c-lpp',
    sources : libasn1c_lpp_sources,
    version : libogslib_version,
    c_args : libasn1c_common_cc_flags,
    include_directories : libasn1c_lpp_inc,
    dependencies : [libasn1c_common_dep, libasn1c_util_dep],
    install : true)

libasn1c_lpp_dep = declare_dependency(
    link_with : libasn1c_lpp,
    include_directories : libasn1c_lpp_inc,
    dependencies : [libasn1c_common_dep, libasn1c_util_dep])
