/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_ARPLocationType_H_
#define	_NRPPA_ARPLocationType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_ARPLocationType_PR {
	NRPPA_ARPLocationType_PR_NOTHING,	/* No components present */
	NRPPA_ARPLocationType_PR_aRPPositionRelativeGeodetic,
	NRPPA_ARPLocationType_PR_aRPPositionRelativeCartesian,
	NRPPA_ARPLocationType_PR_choice_extension
} NRPPA_ARPLocationType_PR;

/* Forward declarations */
struct NRPPA_RelativeGeodeticLocation;
struct NRPPA_RelativeCartesianLocation;
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_ARPLocationType */
typedef struct NRPPA_ARPLocationType {
	NRPPA_ARPLocationType_PR present;
	union NRPPA_ARPLocationType_u {
		struct NRPPA_RelativeGeodeticLocation	*aRPPositionRelativeGeodetic;
		struct NRPPA_RelativeCartesianLocation	*aRPPositionRelativeCartesian;
		struct NRPPA_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_ARPLocationType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ARPLocationType;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_ARPLocationType_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_ARPLocationType_1[3];
extern asn_per_constraints_t asn_PER_type_NRPPA_ARPLocationType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_ARPLocationType_H_ */
#include <asn_internal.h>
