/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_SRSResourceID_Item_H_
#define	_NRPPA_SRSResourceID_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPA_SRSResourceID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_SRSResourceID-Item */
typedef struct NRPPA_SRSResourceID_Item {
	NRPPA_SRSResourceID_t	 sRSResourceID;
	struct NRPPA_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_SRSResourceID_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_SRSResourceID_Item;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_SRSResourceID_Item_H_ */
#include <asn_internal.h>
