/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_TimeWindowDurationSRS_H_
#define	_NRPPA_TimeWindowDurationSRS_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_TimeWindowDurationSRS_PR {
	NRPPA_TimeWindowDurationSRS_PR_NOTHING,	/* No components present */
	NRPPA_TimeWindowDurationSRS_PR_durationSymbols,
	NRPPA_TimeWindowDurationSRS_PR_durationSlots,
	NRPPA_TimeWindowDurationSRS_PR_choice_extension
} NRPPA_TimeWindowDurationSRS_PR;
typedef enum NRPPA_TimeWindowDurationSRS__durationSymbols {
	NRPPA_TimeWindowDurationSRS__durationSymbols_n1	= 0,
	NRPPA_TimeWindowDurationSRS__durationSymbols_n2	= 1,
	NRPPA_TimeWindowDurationSRS__durationSymbols_n4	= 2,
	NRPPA_TimeWindowDurationSRS__durationSymbols_n8	= 3,
	NRPPA_TimeWindowDurationSRS__durationSymbols_n12	= 4
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_TimeWindowDurationSRS__durationSymbols;
typedef enum NRPPA_TimeWindowDurationSRS__durationSlots {
	NRPPA_TimeWindowDurationSRS__durationSlots_n1	= 0,
	NRPPA_TimeWindowDurationSRS__durationSlots_n2	= 1,
	NRPPA_TimeWindowDurationSRS__durationSlots_n4	= 2,
	NRPPA_TimeWindowDurationSRS__durationSlots_n6	= 3,
	NRPPA_TimeWindowDurationSRS__durationSlots_n8	= 4,
	NRPPA_TimeWindowDurationSRS__durationSlots_n12	= 5,
	NRPPA_TimeWindowDurationSRS__durationSlots_n16	= 6
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_TimeWindowDurationSRS__durationSlots;

/* Forward declarations */
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_TimeWindowDurationSRS */
typedef struct NRPPA_TimeWindowDurationSRS {
	NRPPA_TimeWindowDurationSRS_PR present;
	union NRPPA_TimeWindowDurationSRS_u {
		long	 durationSymbols;
		long	 durationSlots;
		struct NRPPA_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TimeWindowDurationSRS_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_durationSymbols_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_durationSlots_9;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TimeWindowDurationSRS;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_TimeWindowDurationSRS_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_TimeWindowDurationSRS_1[3];
extern asn_per_constraints_t asn_PER_type_NRPPA_TimeWindowDurationSRS_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_TimeWindowDurationSRS_H_ */
#include <asn_internal.h>
