/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_ResultSS_RSRP_Item_H_
#define	_NRPPA_ResultSS_RSRP_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPA_NR-PCI.h"
#include "NRPPA_NR-ARFCN.h"
#include "NRPPA_ValueRSRP-NR.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPA_CGI_NR;
struct NRPPA_ResultSS_RSRP_PerSSB;
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_ResultSS-RSRP-Item */
typedef struct NRPPA_ResultSS_RSRP_Item {
	NRPPA_NR_PCI_t	 nR_PCI;
	NRPPA_NR_ARFCN_t	 nR_ARFCN;
	struct NRPPA_CGI_NR	*cGI_NR;	/* OPTIONAL */
	NRPPA_ValueRSRP_NR_t	*valueSS_RSRP_Cell;	/* OPTIONAL */
	struct NRPPA_ResultSS_RSRP_PerSSB	*sS_RSRP_PerSSB;	/* OPTIONAL */
	struct NRPPA_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_ResultSS_RSRP_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ResultSS_RSRP_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_ResultSS_RSRP_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_ResultSS_RSRP_Item_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_ResultSS_RSRP_Item_H_ */
#include <asn_internal.h>
