/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_ULRTOAMeas_H_
#define	_NRPPA_ULRTOAMeas_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_ULRTOAMeas_PR {
	NRPPA_ULRTOAMeas_PR_NOTHING,	/* No components present */
	NRPPA_ULRTOAMeas_PR_k0,
	NRPPA_ULRTOAMeas_PR_k1,
	NRPPA_ULRTOAMeas_PR_k2,
	NRPPA_ULRTOAMeas_PR_k3,
	NRPPA_ULRTOAMeas_PR_k4,
	NRPPA_ULRTOAMeas_PR_k5,
	NRPPA_ULRTOAMeas_PR_choice_extension
} NRPPA_ULRTOAMeas_PR;

/* Forward declarations */
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_ULRTOAMeas */
typedef struct NRPPA_ULRTOAMeas {
	NRPPA_ULRTOAMeas_PR present;
	union NRPPA_ULRTOAMeas_u {
		long	 k0;
		long	 k1;
		long	 k2;
		long	 k3;
		long	 k4;
		long	 k5;
		struct NRPPA_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_ULRTOAMeas_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ULRTOAMeas;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_ULRTOAMeas_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_ULRTOAMeas_1[7];
extern asn_per_constraints_t asn_PER_type_NRPPA_ULRTOAMeas_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_ULRTOAMeas_H_ */
#include <asn_internal.h>
