/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_AngleMeasurementType_H_
#define	_NRPPA_AngleMeasurementType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_AngleMeasurementType_PR {
	NRPPA_AngleMeasurementType_PR_NOTHING,	/* No components present */
	NRPPA_AngleMeasurementType_PR_expected_ULAoA,
	NRPPA_AngleMeasurementType_PR_expected_ZoA,
	NRPPA_AngleMeasurementType_PR_choice_extension
} NRPPA_AngleMeasurementType_PR;

/* Forward declarations */
struct NRPPA_Expected_UL_AoA;
struct NRPPA_Expected_ZoA_only;
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_AngleMeasurementType */
typedef struct NRPPA_AngleMeasurementType {
	NRPPA_AngleMeasurementType_PR present;
	union NRPPA_AngleMeasurementType_u {
		struct NRPPA_Expected_UL_AoA	*expected_ULAoA;
		struct NRPPA_Expected_ZoA_only	*expected_ZoA;
		struct NRPPA_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_AngleMeasurementType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_AngleMeasurementType;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_AngleMeasurementType_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_AngleMeasurementType_1[3];
extern asn_per_constraints_t asn_PER_type_NRPPA_AngleMeasurementType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_AngleMeasurementType_H_ */
#include <asn_internal.h>
