/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_ExtendedResourceSymbolOffset_H_
#define	_NRPPA_ExtendedResourceSymbolOffset_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NRPPA_ExtendedResourceSymbolOffset */
typedef long	 NRPPA_ExtendedResourceSymbolOffset_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPA_ExtendedResourceSymbolOffset_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ExtendedResourceSymbolOffset;
asn_struct_free_f NRPPA_ExtendedResourceSymbolOffset_free;
asn_struct_print_f NRPPA_ExtendedResourceSymbolOffset_print;
asn_constr_check_f NRPPA_ExtendedResourceSymbolOffset_constraint;
per_type_decoder_f NRPPA_ExtendedResourceSymbolOffset_decode_aper;
per_type_encoder_f NRPPA_ExtendedResourceSymbolOffset_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_ExtendedResourceSymbolOffset_H_ */
#include <asn_internal.h>
