/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#include "NRPPA_MeasuredResultsAssociatedInfoItem.h"

#include "NRPPA_TimeStamp.h"
#include "NRPPA_TrpMeasurementQuality.h"
#include "NRPPA_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_NRPPA_MeasuredResultsAssociatedInfoItem_1[] = {
	{ ATF_POINTER, 3, offsetof(struct NRPPA_MeasuredResultsAssociatedInfoItem, timeStamp),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPA_TimeStamp,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"timeStamp"
		},
	{ ATF_POINTER, 2, offsetof(struct NRPPA_MeasuredResultsAssociatedInfoItem, measurementQuality),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NRPPA_TrpMeasurementQuality,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"measurementQuality"
		},
	{ ATF_POINTER, 1, offsetof(struct NRPPA_MeasuredResultsAssociatedInfoItem, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRPPA_ProtocolExtensionContainer_4731P39,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_NRPPA_MeasuredResultsAssociatedInfoItem_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_NRPPA_MeasuredResultsAssociatedInfoItem_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NRPPA_MeasuredResultsAssociatedInfoItem_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* timeStamp */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* measurementQuality */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_NRPPA_MeasuredResultsAssociatedInfoItem_specs_1 = {
	sizeof(struct NRPPA_MeasuredResultsAssociatedInfoItem),
	offsetof(struct NRPPA_MeasuredResultsAssociatedInfoItem, _asn_ctx),
	asn_MAP_NRPPA_MeasuredResultsAssociatedInfoItem_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_NRPPA_MeasuredResultsAssociatedInfoItem_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NRPPA_MeasuredResultsAssociatedInfoItem = {
	"MeasuredResultsAssociatedInfoItem",
	"MeasuredResultsAssociatedInfoItem",
	&asn_OP_SEQUENCE,
	asn_DEF_NRPPA_MeasuredResultsAssociatedInfoItem_tags_1,
	sizeof(asn_DEF_NRPPA_MeasuredResultsAssociatedInfoItem_tags_1)
		/sizeof(asn_DEF_NRPPA_MeasuredResultsAssociatedInfoItem_tags_1[0]), /* 1 */
	asn_DEF_NRPPA_MeasuredResultsAssociatedInfoItem_tags_1,	/* Same as above */
	sizeof(asn_DEF_NRPPA_MeasuredResultsAssociatedInfoItem_tags_1)
		/sizeof(asn_DEF_NRPPA_MeasuredResultsAssociatedInfoItem_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_NRPPA_MeasuredResultsAssociatedInfoItem_1,
	3,	/* Elements count */
	&asn_SPC_NRPPA_MeasuredResultsAssociatedInfoItem_specs_1	/* Additional specs */
};

