/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-CommonDataTypes"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_TriggeringMessage_H_
#define	_NRPPA_TriggeringMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_TriggeringMessage {
	NRPPA_TriggeringMessage_initiating_message	= 0,
	NRPPA_TriggeringMessage_successful_outcome	= 1,
	NRPPA_TriggeringMessage_unsuccessful_outcome	= 2
} e_NRPPA_TriggeringMessage;

/* NRPPA_TriggeringMessage */
typedef long	 NRPPA_TriggeringMessage_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPA_TriggeringMessage_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TriggeringMessage;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPA_TriggeringMessage_specs_1;
asn_struct_free_f NRPPA_TriggeringMessage_free;
asn_struct_print_f NRPPA_TriggeringMessage_print;
asn_constr_check_f NRPPA_TriggeringMessage_constraint;
per_type_decoder_f NRPPA_TriggeringMessage_decode_aper;
per_type_encoder_f NRPPA_TriggeringMessage_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_TriggeringMessage_H_ */
#include <asn_internal.h>
