/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_ResponseTime_H_
#define	_NRPPA_ResponseTime_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_ResponseTime__timeUnit {
	NRPPA_ResponseTime__timeUnit_second	= 0,
	NRPPA_ResponseTime__timeUnit_ten_seconds	= 1,
	NRPPA_ResponseTime__timeUnit_ten_milliseconds	= 2
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_ResponseTime__timeUnit;

/* Forward declarations */
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_ResponseTime */
typedef struct NRPPA_ResponseTime {
	long	 time;
	long	 timeUnit;
	struct NRPPA_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_ResponseTime_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_timeUnit_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ResponseTime;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_ResponseTime_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_ResponseTime_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_ResponseTime_H_ */
#include <asn_internal.h>
