/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_TRPInformationTypeListTRPReq_H_
#define	_NRPPA_TRPInformationTypeListTRPReq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_TRPInformationTypeListTRPReq */
typedef struct NRPPA_TRPInformationTypeListTRPReq {
	A_SEQUENCE_OF(struct NRPPA_ProtocolIE_Single_Container) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TRPInformationTypeListTRPReq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TRPInformationTypeListTRPReq;
extern asn_SET_OF_specifics_t asn_SPC_NRPPA_TRPInformationTypeListTRPReq_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_TRPInformationTypeListTRPReq_1[1];
extern asn_per_constraints_t asn_PER_type_NRPPA_TRPInformationTypeListTRPReq_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_TRPInformationTypeListTRPReq_H_ */
#include <asn_internal.h>
