/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_TRPMeasurementType_H_
#define	_NRPPA_TRPMeasurementType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_TRPMeasurementType {
	NRPPA_TRPMeasurementType_gNB_RxTxTimeDiff	= 0,
	NRPPA_TRPMeasurementType_uL_SRS_RSRP	= 1,
	NRPPA_TRPMeasurementType_uL_AoA	= 2,
	NRPPA_TRPMeasurementType_uL_RTOA	= 3,
	/*
	 * Enumeration is extensible
	 */
	NRPPA_TRPMeasurementType_multiple_UL_AoA	= 4,
	NRPPA_TRPMeasurementType_uL_SRS_RSRPP	= 5,
	NRPPA_TRPMeasurementType_ul_RSCP	= 6,
	NRPPA_TRPMeasurementType_ul_SRS_TDCT	= 7
} e_NRPPA_TRPMeasurementType;

/* NRPPA_TRPMeasurementType */
typedef long	 NRPPA_TRPMeasurementType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPA_TRPMeasurementType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TRPMeasurementType;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPA_TRPMeasurementType_specs_1;
asn_struct_free_f NRPPA_TRPMeasurementType_free;
asn_struct_print_f NRPPA_TRPMeasurementType_print;
asn_constr_check_f NRPPA_TRPMeasurementType_constraint;
per_type_decoder_f NRPPA_TRPMeasurementType_decode_aper;
per_type_encoder_f NRPPA_TRPMeasurementType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_TRPMeasurementType_H_ */
#include <asn_internal.h>
