/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_LoS_NLoSInformation_H_
#define	_NRPPA_LoS_NLoSInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPA_LoS-NLoSIndicatorSoft.h"
#include "NRPPA_LoS-NLoSIndicatorHard.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_LoS_NLoSInformation_PR {
	NRPPA_LoS_NLoSInformation_PR_NOTHING,	/* No components present */
	NRPPA_LoS_NLoSInformation_PR_loS_NLoSIndicatorSoft,
	NRPPA_LoS_NLoSInformation_PR_loS_NLoSIndicatorHard,
	NRPPA_LoS_NLoSInformation_PR_choice_Extension
} NRPPA_LoS_NLoSInformation_PR;

/* Forward declarations */
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_LoS-NLoSInformation */
typedef struct NRPPA_LoS_NLoSInformation {
	NRPPA_LoS_NLoSInformation_PR present;
	union NRPPA_LoS_NLoSInformation_u {
		NRPPA_LoS_NLoSIndicatorSoft_t	 loS_NLoSIndicatorSoft;
		NRPPA_LoS_NLoSIndicatorHard_t	 loS_NLoSIndicatorHard;
		struct NRPPA_ProtocolIE_Single_Container	*choice_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_LoS_NLoSInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_LoS_NLoSInformation;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_LoS_NLoSInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_LoS_NLoSInformation_1[3];
extern asn_per_constraints_t asn_PER_type_NRPPA_LoS_NLoSInformation_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_LoS_NLoSInformation_H_ */
#include <asn_internal.h>
