/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_MeasurementPeriodicityExtended_H_
#define	_NRPPA_MeasurementPeriodicityExtended_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_MeasurementPeriodicityExtended {
	NRPPA_MeasurementPeriodicityExtended_ms160	= 0,
	NRPPA_MeasurementPeriodicityExtended_ms320	= 1,
	NRPPA_MeasurementPeriodicityExtended_ms1280	= 2,
	NRPPA_MeasurementPeriodicityExtended_ms2560	= 3,
	NRPPA_MeasurementPeriodicityExtended_ms61440	= 4,
	NRPPA_MeasurementPeriodicityExtended_ms81920	= 5,
	NRPPA_MeasurementPeriodicityExtended_ms368640	= 6,
	NRPPA_MeasurementPeriodicityExtended_ms737280	= 7,
	NRPPA_MeasurementPeriodicityExtended_ms1843200	= 8
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_MeasurementPeriodicityExtended;

/* NRPPA_MeasurementPeriodicityExtended */
typedef long	 NRPPA_MeasurementPeriodicityExtended_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPA_MeasurementPeriodicityExtended_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_MeasurementPeriodicityExtended;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPA_MeasurementPeriodicityExtended_specs_1;
asn_struct_free_f NRPPA_MeasurementPeriodicityExtended_free;
asn_struct_print_f NRPPA_MeasurementPeriodicityExtended_print;
asn_constr_check_f NRPPA_MeasurementPeriodicityExtended_constraint;
per_type_decoder_f NRPPA_MeasurementPeriodicityExtended_decode_aper;
per_type_encoder_f NRPPA_MeasurementPeriodicityExtended_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_MeasurementPeriodicityExtended_H_ */
#include <asn_internal.h>
