/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_ResultUTRAN_Item_H_
#define	_NRPPA_ResultUTRAN_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPA_UARFCN.h"
#include "NRPPA_UTRA-RSCP.h"
#include "NRPPA_UTRA-EcN0.h"
#include "NRPPA_PhysCellIDUTRA-FDD.h"
#include "NRPPA_PhysCellIDUTRA-TDD.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_ResultUTRAN_Item__physCellIDUTRAN_PR {
	NRPPA_ResultUTRAN_Item__physCellIDUTRAN_PR_NOTHING,	/* No components present */
	NRPPA_ResultUTRAN_Item__physCellIDUTRAN_PR_physCellIDUTRA_FDD,
	NRPPA_ResultUTRAN_Item__physCellIDUTRAN_PR_physCellIDUTRA_TDD
} NRPPA_ResultUTRAN_Item__physCellIDUTRAN_PR;

/* Forward declarations */
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_ResultUTRAN-Item */
typedef struct NRPPA_ResultUTRAN_Item {
	NRPPA_UARFCN_t	 uARFCN;
	struct NRPPA_ResultUTRAN_Item__physCellIDUTRAN {
		NRPPA_ResultUTRAN_Item__physCellIDUTRAN_PR present;
		union NRPPA_ResultUTRAN_Item__NRPPA_physCellIDUTRAN_u {
			NRPPA_PhysCellIDUTRA_FDD_t	 physCellIDUTRA_FDD;
			NRPPA_PhysCellIDUTRA_TDD_t	 physCellIDUTRA_TDD;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} physCellIDUTRAN;
	NRPPA_UTRA_RSCP_t	*uTRA_RSCP;	/* OPTIONAL */
	NRPPA_UTRA_EcN0_t	*uTRA_EcN0;	/* OPTIONAL */
	struct NRPPA_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_ResultUTRAN_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ResultUTRAN_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_ResultUTRAN_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_ResultUTRAN_Item_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_ResultUTRAN_Item_H_ */
#include <asn_internal.h>
