/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_ActiveULBWP_H_
#define	_NRPPA_ActiveULBWP_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include "NRPPA_SRSConfig.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_ActiveULBWP__subcarrierSpacing {
	NRPPA_ActiveULBWP__subcarrierSpacing_kHz15	= 0,
	NRPPA_ActiveULBWP__subcarrierSpacing_kHz30	= 1,
	NRPPA_ActiveULBWP__subcarrierSpacing_kHz60	= 2,
	NRPPA_ActiveULBWP__subcarrierSpacing_kHz120	= 3,
	/*
	 * Enumeration is extensible
	 */
	NRPPA_ActiveULBWP__subcarrierSpacing_kHz480	= 4,
	NRPPA_ActiveULBWP__subcarrierSpacing_kHz960	= 5
} e_NRPPA_ActiveULBWP__subcarrierSpacing;
typedef enum NRPPA_ActiveULBWP__cyclicPrefix {
	NRPPA_ActiveULBWP__cyclicPrefix_normal	= 0,
	NRPPA_ActiveULBWP__cyclicPrefix_extended	= 1
} e_NRPPA_ActiveULBWP__cyclicPrefix;
typedef enum NRPPA_ActiveULBWP__shift7dot5kHz {
	NRPPA_ActiveULBWP__shift7dot5kHz_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_ActiveULBWP__shift7dot5kHz;

/* Forward declarations */
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_ActiveULBWP */
typedef struct NRPPA_ActiveULBWP {
	long	 locationAndBandwidth;
	long	 subcarrierSpacing;
	long	 cyclicPrefix;
	long	 txDirectCurrentLocation;
	long	*shift7dot5kHz;	/* OPTIONAL */
	NRPPA_SRSConfig_t	 sRSConfig;
	struct NRPPA_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_ActiveULBWP_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_subcarrierSpacing_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_cyclicPrefix_11;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_shift7dot5kHz_15;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ActiveULBWP;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_ActiveULBWP_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_ActiveULBWP_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_ActiveULBWP_H_ */
#include <asn_internal.h>
