/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_MeasurementAmount_H_
#define	_NRPPA_MeasurementAmount_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_MeasurementAmount {
	NRPPA_MeasurementAmount_ma0	= 0,
	NRPPA_MeasurementAmount_ma1	= 1,
	NRPPA_MeasurementAmount_ma2	= 2,
	NRPPA_MeasurementAmount_ma4	= 3,
	NRPPA_MeasurementAmount_ma8	= 4,
	NRPPA_MeasurementAmount_ma16	= 5,
	NRPPA_MeasurementAmount_ma32	= 6,
	NRPPA_MeasurementAmount_ma64	= 7
} e_NRPPA_MeasurementAmount;

/* NRPPA_MeasurementAmount */
typedef long	 NRPPA_MeasurementAmount_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPA_MeasurementAmount_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_MeasurementAmount;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPA_MeasurementAmount_specs_1;
asn_struct_free_f NRPPA_MeasurementAmount_free;
asn_struct_print_f NRPPA_MeasurementAmount_print;
asn_constr_check_f NRPPA_MeasurementAmount_constraint;
per_type_decoder_f NRPPA_MeasurementAmount_decode_aper;
per_type_encoder_f NRPPA_MeasurementAmount_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_MeasurementAmount_H_ */
#include <asn_internal.h>
