/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_TimeWindowPeriodicityMeasurement_H_
#define	_NRPPA_TimeWindowPeriodicityMeasurement_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_TimeWindowPeriodicityMeasurement {
	NRPPA_TimeWindowPeriodicityMeasurement_ms160	= 0,
	NRPPA_TimeWindowPeriodicityMeasurement_ms320	= 1,
	NRPPA_TimeWindowPeriodicityMeasurement_ms640	= 2,
	NRPPA_TimeWindowPeriodicityMeasurement_ms1280	= 3,
	NRPPA_TimeWindowPeriodicityMeasurement_ms2560	= 4,
	NRPPA_TimeWindowPeriodicityMeasurement_ms5120	= 5,
	NRPPA_TimeWindowPeriodicityMeasurement_ms10240	= 6,
	NRPPA_TimeWindowPeriodicityMeasurement_ms20480	= 7,
	NRPPA_TimeWindowPeriodicityMeasurement_ms40960	= 8,
	NRPPA_TimeWindowPeriodicityMeasurement_ms61440	= 9,
	NRPPA_TimeWindowPeriodicityMeasurement_ms81920	= 10,
	NRPPA_TimeWindowPeriodicityMeasurement_ms368640	= 11,
	NRPPA_TimeWindowPeriodicityMeasurement_ms737280	= 12,
	NRPPA_TimeWindowPeriodicityMeasurement_ms1843200	= 13
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_TimeWindowPeriodicityMeasurement;

/* NRPPA_TimeWindowPeriodicityMeasurement */
typedef long	 NRPPA_TimeWindowPeriodicityMeasurement_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPA_TimeWindowPeriodicityMeasurement_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TimeWindowPeriodicityMeasurement;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPA_TimeWindowPeriodicityMeasurement_specs_1;
asn_struct_free_f NRPPA_TimeWindowPeriodicityMeasurement_free;
asn_struct_print_f NRPPA_TimeWindowPeriodicityMeasurement_print;
asn_constr_check_f NRPPA_TimeWindowPeriodicityMeasurement_constraint;
per_type_decoder_f NRPPA_TimeWindowPeriodicityMeasurement_decode_aper;
per_type_encoder_f NRPPA_TimeWindowPeriodicityMeasurement_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_TimeWindowPeriodicityMeasurement_H_ */
#include <asn_internal.h>
