/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_ResourceTypeSemi_persistentPos_H_
#define	_NRPPA_ResourceTypeSemi_persistentPos_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPA_SRSPeriodicity.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_ResourceTypeSemi-persistentPos */
typedef struct NRPPA_ResourceTypeSemi_persistentPos {
	NRPPA_SRSPeriodicity_t	 sRSPeriodicity;
	long	 offset;
	struct NRPPA_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_ResourceTypeSemi_persistentPos_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ResourceTypeSemi_persistentPos;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_ResourceTypeSemi_persistentPos_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_ResourceTypeSemi_persistentPos_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_ResourceTypeSemi_persistentPos_H_ */
#include <asn_internal.h>
