/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_SlotOffsetRemainingHops_H_
#define	_NRPPA_SlotOffsetRemainingHops_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_SlotOffsetRemainingHops_PR {
	NRPPA_SlotOffsetRemainingHops_PR_NOTHING,	/* No components present */
	NRPPA_SlotOffsetRemainingHops_PR_aperiodic,
	NRPPA_SlotOffsetRemainingHops_PR_semi_persistent,
	NRPPA_SlotOffsetRemainingHops_PR_periodic,
	NRPPA_SlotOffsetRemainingHops_PR_choice_extension
} NRPPA_SlotOffsetRemainingHops_PR;

/* Forward declarations */
struct NRPPA_SlotOffsetRemainingHopsAperiodic;
struct NRPPA_SlotOffsetRemainingHopsSemiPersistent;
struct NRPPA_SlotOffsetRemainingHopsPeriodic;
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_SlotOffsetRemainingHops */
typedef struct NRPPA_SlotOffsetRemainingHops {
	NRPPA_SlotOffsetRemainingHops_PR present;
	union NRPPA_SlotOffsetRemainingHops_u {
		struct NRPPA_SlotOffsetRemainingHopsAperiodic	*aperiodic;
		struct NRPPA_SlotOffsetRemainingHopsSemiPersistent	*semi_persistent;
		struct NRPPA_SlotOffsetRemainingHopsPeriodic	*periodic;
		struct NRPPA_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_SlotOffsetRemainingHops_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_SlotOffsetRemainingHops;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_SlotOffsetRemainingHops_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_SlotOffsetRemainingHops_1[4];
extern asn_per_constraints_t asn_PER_type_NRPPA_SlotOffsetRemainingHops_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_SlotOffsetRemainingHops_H_ */
#include <asn_internal.h>
