/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_TRP_Measurement_Item_H_
#define	_NRPPA_TRP_Measurement_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPA_TRP-ID.h"
#include "NRPPA_TimeStamp.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPA_UL_RTOAMeasurement;
struct NRPPA_GNB_RxTxTimeDiff;
struct NRPPA_LoS_NLoSInformation;
struct NRPPA_TrpMeasurementQuality;
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_TRP-Measurement-Item */
typedef struct NRPPA_TRP_Measurement_Item {
	NRPPA_TRP_ID_t	 tRP_ID;
	struct NRPPA_UL_RTOAMeasurement	*uL_RTOA;	/* OPTIONAL */
	struct NRPPA_GNB_RxTxTimeDiff	*gNB_RxTxTimeDiff;	/* OPTIONAL */
	struct NRPPA_LoS_NLoSInformation	*los_nlos_info;	/* OPTIONAL */
	NRPPA_TimeStamp_t	 timeStamp;
	struct NRPPA_TrpMeasurementQuality	*measurementQuality;	/* OPTIONAL */
	struct NRPPA_ProtocolExtensionContainer	*iE_extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TRP_Measurement_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TRP_Measurement_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_TRP_Measurement_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_TRP_Measurement_Item_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_TRP_Measurement_Item_H_ */
#include <asn_internal.h>
