/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_PathlossReferenceSignal_H_
#define	_NRPPA_PathlossReferenceSignal_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_PathlossReferenceSignal_PR {
	NRPPA_PathlossReferenceSignal_PR_NOTHING,	/* No components present */
	NRPPA_PathlossReferenceSignal_PR_sSB_Reference,
	NRPPA_PathlossReferenceSignal_PR_dL_PRS_Reference,
	NRPPA_PathlossReferenceSignal_PR_choice_Extension
} NRPPA_PathlossReferenceSignal_PR;

/* Forward declarations */
struct NRPPA_SSB;
struct NRPPA_DL_PRS;
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_PathlossReferenceSignal */
typedef struct NRPPA_PathlossReferenceSignal {
	NRPPA_PathlossReferenceSignal_PR present;
	union NRPPA_PathlossReferenceSignal_u {
		struct NRPPA_SSB	*sSB_Reference;
		struct NRPPA_DL_PRS	*dL_PRS_Reference;
		struct NRPPA_ProtocolIE_Single_Container	*choice_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PathlossReferenceSignal_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PathlossReferenceSignal;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_PathlossReferenceSignal_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_PathlossReferenceSignal_1[3];
extern asn_per_constraints_t asn_PER_type_NRPPA_PathlossReferenceSignal_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_PathlossReferenceSignal_H_ */
#include <asn_internal.h>
