/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_Mobile_TRP_LocationInformation_H_
#define	_NRPPA_Mobile_TRP_LocationInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPA_TimeStamp;
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_Mobile-TRP-LocationInformation */
typedef struct NRPPA_Mobile_TRP_LocationInformation {
	OCTET_STRING_t	 location_Information;
	OCTET_STRING_t	*velocity_Information;	/* OPTIONAL */
	struct NRPPA_TimeStamp	*location_time_stamp;	/* OPTIONAL */
	struct NRPPA_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_Mobile_TRP_LocationInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_Mobile_TRP_LocationInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_Mobile_TRP_LocationInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_Mobile_TRP_LocationInformation_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_Mobile_TRP_LocationInformation_H_ */
#include <asn_internal.h>
