/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_UL_SRS_TDCP_Item_H_
#define	_NRPPA_UL_SRS_TDCP_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NRPPA_UL-SRS-TDCP-Item */
typedef long	 NRPPA_UL_SRS_TDCP_Item_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPA_UL_SRS_TDCP_Item_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_UL_SRS_TDCP_Item;
asn_struct_free_f NRPPA_UL_SRS_TDCP_Item_free;
asn_struct_print_f NRPPA_UL_SRS_TDCP_Item_print;
asn_constr_check_f NRPPA_UL_SRS_TDCP_Item_constraint;
per_type_decoder_f NRPPA_UL_SRS_TDCP_Item_decode_aper;
per_type_encoder_f NRPPA_UL_SRS_TDCP_Item_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_UL_SRS_TDCP_Item_H_ */
#include <asn_internal.h>
