/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_OtherRATMeasurementQuantitiesValue_H_
#define	_NRPPA_OtherRATMeasurementQuantitiesValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_OtherRATMeasurementQuantitiesValue {
	NRPPA_OtherRATMeasurementQuantitiesValue_geran	= 0,
	NRPPA_OtherRATMeasurementQuantitiesValue_utran	= 1,
	/*
	 * Enumeration is extensible
	 */
	NRPPA_OtherRATMeasurementQuantitiesValue_nR	= 2,
	NRPPA_OtherRATMeasurementQuantitiesValue_eUTRA	= 3
} e_NRPPA_OtherRATMeasurementQuantitiesValue;

/* NRPPA_OtherRATMeasurementQuantitiesValue */
typedef long	 NRPPA_OtherRATMeasurementQuantitiesValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPA_OtherRATMeasurementQuantitiesValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_OtherRATMeasurementQuantitiesValue;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPA_OtherRATMeasurementQuantitiesValue_specs_1;
asn_struct_free_f NRPPA_OtherRATMeasurementQuantitiesValue_free;
asn_struct_print_f NRPPA_OtherRATMeasurementQuantitiesValue_print;
asn_constr_check_f NRPPA_OtherRATMeasurementQuantitiesValue_constraint;
per_type_decoder_f NRPPA_OtherRATMeasurementQuantitiesValue_decode_aper;
per_type_encoder_f NRPPA_OtherRATMeasurementQuantitiesValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_OtherRATMeasurementQuantitiesValue_H_ */
#include <asn_internal.h>
