/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_ResourceTypePos_H_
#define	_NRPPA_ResourceTypePos_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_ResourceTypePos_PR {
	NRPPA_ResourceTypePos_PR_NOTHING,	/* No components present */
	NRPPA_ResourceTypePos_PR_periodic,
	NRPPA_ResourceTypePos_PR_semi_persistent,
	NRPPA_ResourceTypePos_PR_aperiodic,
	NRPPA_ResourceTypePos_PR_choice_extension
} NRPPA_ResourceTypePos_PR;

/* Forward declarations */
struct NRPPA_ResourceTypePeriodicPos;
struct NRPPA_ResourceTypeSemi_persistentPos;
struct NRPPA_ResourceTypeAperiodicPos;
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_ResourceTypePos */
typedef struct NRPPA_ResourceTypePos {
	NRPPA_ResourceTypePos_PR present;
	union NRPPA_ResourceTypePos_u {
		struct NRPPA_ResourceTypePeriodicPos	*periodic;
		struct NRPPA_ResourceTypeSemi_persistentPos	*semi_persistent;
		struct NRPPA_ResourceTypeAperiodicPos	*aperiodic;
		struct NRPPA_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_ResourceTypePos_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ResourceTypePos;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_ResourceTypePos_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_ResourceTypePos_1[4];
extern asn_per_constraints_t asn_PER_type_NRPPA_ResourceTypePos_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_ResourceTypePos_H_ */
#include <asn_internal.h>
