/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_UEReportingInformation_H_
#define	_NRPPA_UEReportingInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_UEReportingInformation__reportingAmount {
	NRPPA_UEReportingInformation__reportingAmount_ma0	= 0,
	NRPPA_UEReportingInformation__reportingAmount_ma1	= 1,
	NRPPA_UEReportingInformation__reportingAmount_ma2	= 2,
	NRPPA_UEReportingInformation__reportingAmount_ma4	= 3,
	NRPPA_UEReportingInformation__reportingAmount_ma8	= 4,
	NRPPA_UEReportingInformation__reportingAmount_ma16	= 5,
	NRPPA_UEReportingInformation__reportingAmount_ma32	= 6,
	NRPPA_UEReportingInformation__reportingAmount_ma64	= 7
} e_NRPPA_UEReportingInformation__reportingAmount;
typedef enum NRPPA_UEReportingInformation__reportingInterval {
	NRPPA_UEReportingInformation__reportingInterval_none	= 0,
	NRPPA_UEReportingInformation__reportingInterval_one	= 1,
	NRPPA_UEReportingInformation__reportingInterval_two	= 2,
	NRPPA_UEReportingInformation__reportingInterval_four	= 3,
	NRPPA_UEReportingInformation__reportingInterval_eight	= 4,
	NRPPA_UEReportingInformation__reportingInterval_ten	= 5,
	NRPPA_UEReportingInformation__reportingInterval_sixteen	= 6,
	NRPPA_UEReportingInformation__reportingInterval_twenty	= 7,
	NRPPA_UEReportingInformation__reportingInterval_thirty_two	= 8,
	NRPPA_UEReportingInformation__reportingInterval_sixty_four	= 9
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_UEReportingInformation__reportingInterval;

/* Forward declarations */
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_UEReportingInformation */
typedef struct NRPPA_UEReportingInformation {
	long	 reportingAmount;
	long	 reportingInterval;
	struct NRPPA_ProtocolExtensionContainer	*iE_extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_UEReportingInformation_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_reportingAmount_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_reportingInterval_11;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_UEReportingInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_UEReportingInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_UEReportingInformation_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_UEReportingInformation_H_ */
#include <asn_internal.h>
