/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_PRSConfigRequestType_H_
#define	_NRPPA_PRSConfigRequestType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_PRSConfigRequestType {
	NRPPA_PRSConfigRequestType_configure	= 0,
	NRPPA_PRSConfigRequestType_off	= 1
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_PRSConfigRequestType;

/* NRPPA_PRSConfigRequestType */
typedef long	 NRPPA_PRSConfigRequestType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPA_PRSConfigRequestType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PRSConfigRequestType;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPA_PRSConfigRequestType_specs_1;
asn_struct_free_f NRPPA_PRSConfigRequestType_free;
asn_struct_print_f NRPPA_PRSConfigRequestType_print;
asn_constr_check_f NRPPA_PRSConfigRequestType_constraint;
per_type_decoder_f NRPPA_PRSConfigRequestType_decode_aper;
per_type_encoder_f NRPPA_PRSConfigRequestType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_PRSConfigRequestType_H_ */
#include <asn_internal.h>
