/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_PeriodicityItem_H_
#define	_NRPPA_PeriodicityItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_PeriodicityItem {
	NRPPA_PeriodicityItem_ms0dot125	= 0,
	NRPPA_PeriodicityItem_ms0dot25	= 1,
	NRPPA_PeriodicityItem_ms0dot5	= 2,
	NRPPA_PeriodicityItem_ms0dot625	= 3,
	NRPPA_PeriodicityItem_ms1	= 4,
	NRPPA_PeriodicityItem_ms1dot25	= 5,
	NRPPA_PeriodicityItem_ms2	= 6,
	NRPPA_PeriodicityItem_ms2dot5	= 7,
	NRPPA_PeriodicityItem_ms4dot	= 8,
	NRPPA_PeriodicityItem_ms5	= 9,
	NRPPA_PeriodicityItem_ms8	= 10,
	NRPPA_PeriodicityItem_ms10	= 11,
	NRPPA_PeriodicityItem_ms16	= 12,
	NRPPA_PeriodicityItem_ms20	= 13,
	NRPPA_PeriodicityItem_ms32	= 14,
	NRPPA_PeriodicityItem_ms40	= 15,
	NRPPA_PeriodicityItem_ms64	= 16,
	NRPPA_PeriodicityItem_ms80m	= 17,
	NRPPA_PeriodicityItem_ms160	= 18,
	NRPPA_PeriodicityItem_ms320	= 19,
	NRPPA_PeriodicityItem_ms640m	= 20,
	NRPPA_PeriodicityItem_ms1280	= 21,
	NRPPA_PeriodicityItem_ms2560	= 22,
	NRPPA_PeriodicityItem_ms5120	= 23,
	NRPPA_PeriodicityItem_ms10240	= 24
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_PeriodicityItem;

/* NRPPA_PeriodicityItem */
typedef long	 NRPPA_PeriodicityItem_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPA_PeriodicityItem_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PeriodicityItem;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPA_PeriodicityItem_specs_1;
asn_struct_free_f NRPPA_PeriodicityItem_free;
asn_struct_print_f NRPPA_PeriodicityItem_print;
asn_constr_check_f NRPPA_PeriodicityItem_constraint;
per_type_decoder_f NRPPA_PeriodicityItem_decode_aper;
per_type_encoder_f NRPPA_PeriodicityItem_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_PeriodicityItem_H_ */
#include <asn_internal.h>
