/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_PRSMutingConfiguration_EUTRA_H_
#define	_NRPPA_PRSMutingConfiguration_EUTRA_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_PRSMutingConfiguration_EUTRA_PR {
	NRPPA_PRSMutingConfiguration_EUTRA_PR_NOTHING,	/* No components present */
	NRPPA_PRSMutingConfiguration_EUTRA_PR_two,
	NRPPA_PRSMutingConfiguration_EUTRA_PR_four,
	NRPPA_PRSMutingConfiguration_EUTRA_PR_eight,
	NRPPA_PRSMutingConfiguration_EUTRA_PR_sixteen,
	NRPPA_PRSMutingConfiguration_EUTRA_PR_thirty_two,
	NRPPA_PRSMutingConfiguration_EUTRA_PR_sixty_four,
	NRPPA_PRSMutingConfiguration_EUTRA_PR_one_hundred_and_twenty_eight,
	NRPPA_PRSMutingConfiguration_EUTRA_PR_two_hundred_and_fifty_six,
	NRPPA_PRSMutingConfiguration_EUTRA_PR_five_hundred_and_twelve,
	NRPPA_PRSMutingConfiguration_EUTRA_PR_one_thousand_and_twenty_four,
	NRPPA_PRSMutingConfiguration_EUTRA_PR_choice_Extension
} NRPPA_PRSMutingConfiguration_EUTRA_PR;

/* Forward declarations */
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_PRSMutingConfiguration-EUTRA */
typedef struct NRPPA_PRSMutingConfiguration_EUTRA {
	NRPPA_PRSMutingConfiguration_EUTRA_PR present;
	union NRPPA_PRSMutingConfiguration_EUTRA_u {
		BIT_STRING_t	 two;
		BIT_STRING_t	 four;
		BIT_STRING_t	 eight;
		BIT_STRING_t	 sixteen;
		BIT_STRING_t	 thirty_two;
		BIT_STRING_t	 sixty_four;
		BIT_STRING_t	 one_hundred_and_twenty_eight;
		BIT_STRING_t	 two_hundred_and_fifty_six;
		BIT_STRING_t	 five_hundred_and_twelve;
		BIT_STRING_t	 one_thousand_and_twenty_four;
		struct NRPPA_ProtocolIE_Single_Container	*choice_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PRSMutingConfiguration_EUTRA_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PRSMutingConfiguration_EUTRA;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_PRSMutingConfiguration_EUTRA_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_PRSMutingConfiguration_EUTRA_1[11];
extern asn_per_constraints_t asn_PER_type_NRPPA_PRSMutingConfiguration_EUTRA_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_PRSMutingConfiguration_EUTRA_H_ */
#include <asn_internal.h>
