/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_TxHoppingConfiguration_H_
#define	_NRPPA_TxHoppingConfiguration_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include "NRPPA_SlotOffsetForRemainingHopsList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_TxHoppingConfiguration__overlapValue {
	NRPPA_TxHoppingConfiguration__overlapValue_rb0	= 0,
	NRPPA_TxHoppingConfiguration__overlapValue_rb1	= 1,
	NRPPA_TxHoppingConfiguration__overlapValue_rb2	= 2,
	NRPPA_TxHoppingConfiguration__overlapValue_rb4	= 3
} e_NRPPA_TxHoppingConfiguration__overlapValue;

/* Forward declarations */
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_TxHoppingConfiguration */
typedef struct NRPPA_TxHoppingConfiguration {
	long	 overlapValue;
	long	 numberOfHops;
	NRPPA_SlotOffsetForRemainingHopsList_t	 slotOffsetForRemainingHopsList;
	struct NRPPA_ProtocolExtensionContainer	*iE_extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TxHoppingConfiguration_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_overlapValue_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TxHoppingConfiguration;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_TxHoppingConfiguration_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_TxHoppingConfiguration_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_TxHoppingConfiguration_H_ */
#include <asn_internal.h>
