/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_TimeWindowInformation_Measurement_Item_H_
#define	_NRPPA_TimeWindowInformation_Measurement_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPA_TimeWindowDurationMeasurement.h"
#include <NativeEnumerated.h>
#include "NRPPA_TimeWindowPeriodicityMeasurement.h"
#include "NRPPA_TimeWindowStart.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_TimeWindowInformation_Measurement_Item__timeWindowType {
	NRPPA_TimeWindowInformation_Measurement_Item__timeWindowType_single	= 0,
	NRPPA_TimeWindowInformation_Measurement_Item__timeWindowType_periodic	= 1
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_TimeWindowInformation_Measurement_Item__timeWindowType;

/* Forward declarations */
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_TimeWindowInformation-Measurement-Item */
typedef struct NRPPA_TimeWindowInformation_Measurement_Item {
	NRPPA_TimeWindowDurationMeasurement_t	 timeWindowDurationMeasurement;
	long	 timeWindowType;
	NRPPA_TimeWindowPeriodicityMeasurement_t	*timeWindowPeriodicityMeasurement;	/* OPTIONAL */
	NRPPA_TimeWindowStart_t	 timeWindowStart;
	struct NRPPA_ProtocolExtensionContainer	*iE_Extension;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TimeWindowInformation_Measurement_Item_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_timeWindowType_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TimeWindowInformation_Measurement_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_TimeWindowInformation_Measurement_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_TimeWindowInformation_Measurement_Item_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_TimeWindowInformation_Measurement_Item_H_ */
#include <asn_internal.h>
