/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_ResourceSetType_H_
#define	_NRPPA_ResourceSetType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_ResourceSetType_PR {
	NRPPA_ResourceSetType_PR_NOTHING,	/* No components present */
	NRPPA_ResourceSetType_PR_periodic,
	NRPPA_ResourceSetType_PR_semi_persistent,
	NRPPA_ResourceSetType_PR_aperiodic,
	NRPPA_ResourceSetType_PR_choice_extension
} NRPPA_ResourceSetType_PR;

/* Forward declarations */
struct NRPPA_ResourceSetTypePeriodic;
struct NRPPA_ResourceSetTypeSemi_persistent;
struct NRPPA_ResourceSetTypeAperiodic;
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_ResourceSetType */
typedef struct NRPPA_ResourceSetType {
	NRPPA_ResourceSetType_PR present;
	union NRPPA_ResourceSetType_u {
		struct NRPPA_ResourceSetTypePeriodic	*periodic;
		struct NRPPA_ResourceSetTypeSemi_persistent	*semi_persistent;
		struct NRPPA_ResourceSetTypeAperiodic	*aperiodic;
		struct NRPPA_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_ResourceSetType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_ResourceSetType;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_ResourceSetType_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_ResourceSetType_1[4];
extern asn_per_constraints_t asn_PER_type_NRPPA_ResourceSetType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_ResourceSetType_H_ */
#include <asn_internal.h>
