/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_SRSResourceTypeChoice_H_
#define	_NRPPA_SRSResourceTypeChoice_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_SRSResourceTypeChoice_PR {
	NRPPA_SRSResourceTypeChoice_PR_NOTHING,	/* No components present */
	NRPPA_SRSResourceTypeChoice_PR_sRSResourceInfo,
	NRPPA_SRSResourceTypeChoice_PR_posSRSResourceInfo
	/* Extensions may appear below */
	
} NRPPA_SRSResourceTypeChoice_PR;

/* Forward declarations */
struct NRPPA_SRSInfo;
struct NRPPA_PosSRSInfo;

/* NRPPA_SRSResourceTypeChoice */
typedef struct NRPPA_SRSResourceTypeChoice {
	NRPPA_SRSResourceTypeChoice_PR present;
	union NRPPA_SRSResourceTypeChoice_u {
		struct NRPPA_SRSInfo	*sRSResourceInfo;
		struct NRPPA_PosSRSInfo	*posSRSResourceInfo;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_SRSResourceTypeChoice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_SRSResourceTypeChoice;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_SRSResourceTypeChoice_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_SRSResourceTypeChoice_1[2];
extern asn_per_constraints_t asn_PER_type_NRPPA_SRSResourceTypeChoice_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_SRSResourceTypeChoice_H_ */
#include <asn_internal.h>
