/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-PDU-Contents"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_PositioningInformationResponse_H_
#define	_NRPPA_PositioningInformationResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPPA_ProtocolIE-Container.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NRPPA_PositioningInformationResponse */
typedef struct NRPPA_PositioningInformationResponse {
	NRPPA_ProtocolIE_Container_4708P13_t	 protocolIEs;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PositioningInformationResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PositioningInformationResponse;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_PositioningInformationResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_PositioningInformationResponse_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_PositioningInformationResponse_H_ */
#include <asn_internal.h>
