/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_StartRBIndex_H_
#define	_NRPPA_StartRBIndex_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_StartRBIndex_PR {
	NRPPA_StartRBIndex_PR_NOTHING,	/* No components present */
	NRPPA_StartRBIndex_PR_freqScalingFactor2,
	NRPPA_StartRBIndex_PR_freqScalingFactor4,
	NRPPA_StartRBIndex_PR_choice_extension
} NRPPA_StartRBIndex_PR;

/* Forward declarations */
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_StartRBIndex */
typedef struct NRPPA_StartRBIndex {
	NRPPA_StartRBIndex_PR present;
	union NRPPA_StartRBIndex_u {
		long	 freqScalingFactor2;
		long	 freqScalingFactor4;
		struct NRPPA_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_StartRBIndex_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_StartRBIndex;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_StartRBIndex_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_StartRBIndex_1[3];
extern asn_per_constraints_t asn_PER_type_NRPPA_StartRBIndex_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_StartRBIndex_H_ */
#include <asn_internal.h>
