/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_TRPInformationTypeResponseItem_H_
#define	_NRPPA_TRPInformationTypeResponseItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "NRPPA_RelativeTime1900.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_TRPInformationTypeResponseItem_PR {
	NRPPA_TRPInformationTypeResponseItem_PR_NOTHING,	/* No components present */
	NRPPA_TRPInformationTypeResponseItem_PR_pCI_NR,
	NRPPA_TRPInformationTypeResponseItem_PR_cGI_NR,
	NRPPA_TRPInformationTypeResponseItem_PR_aRFCN,
	NRPPA_TRPInformationTypeResponseItem_PR_pRSConfiguration,
	NRPPA_TRPInformationTypeResponseItem_PR_sSBinformation,
	NRPPA_TRPInformationTypeResponseItem_PR_sFNInitialisationTime,
	NRPPA_TRPInformationTypeResponseItem_PR_spatialDirectionInformation,
	NRPPA_TRPInformationTypeResponseItem_PR_geographicalCoordinates,
	NRPPA_TRPInformationTypeResponseItem_PR_choice_extension
} NRPPA_TRPInformationTypeResponseItem_PR;

/* Forward declarations */
struct NRPPA_CGI_NR;
struct NRPPA_PRSConfiguration;
struct NRPPA_SSBInfo;
struct NRPPA_SpatialDirectionInformation;
struct NRPPA_GeographicalCoordinates;
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_TRPInformationTypeResponseItem */
typedef struct NRPPA_TRPInformationTypeResponseItem {
	NRPPA_TRPInformationTypeResponseItem_PR present;
	union NRPPA_TRPInformationTypeResponseItem_u {
		long	 pCI_NR;
		struct NRPPA_CGI_NR	*cGI_NR;
		long	 aRFCN;
		struct NRPPA_PRSConfiguration	*pRSConfiguration;
		struct NRPPA_SSBInfo	*sSBinformation;
		NRPPA_RelativeTime1900_t	 sFNInitialisationTime;
		struct NRPPA_SpatialDirectionInformation	*spatialDirectionInformation;
		struct NRPPA_GeographicalCoordinates	*geographicalCoordinates;
		struct NRPPA_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_TRPInformationTypeResponseItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_TRPInformationTypeResponseItem;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_TRPInformationTypeResponseItem_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_TRPInformationTypeResponseItem_1[9];
extern asn_per_constraints_t asn_PER_type_NRPPA_TRPInformationTypeResponseItem_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_TRPInformationTypeResponseItem_H_ */
#include <asn_internal.h>
