/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_PRSTransmissionOffIndication_H_
#define	_NRPPA_PRSTransmissionOffIndication_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_PRSTransmissionOffIndication_PR {
	NRPPA_PRSTransmissionOffIndication_PR_NOTHING,	/* No components present */
	NRPPA_PRSTransmissionOffIndication_PR_pRSTransmissionOffPerTRP,
	NRPPA_PRSTransmissionOffIndication_PR_pRSTransmissionOffPerResourceSet,
	NRPPA_PRSTransmissionOffIndication_PR_pRSTransmissionOffPerResource,
	NRPPA_PRSTransmissionOffIndication_PR_choice_Extension
} NRPPA_PRSTransmissionOffIndication_PR;

/* Forward declarations */
struct NRPPA_PRSTransmissionOffPerResourceSet;
struct NRPPA_PRSTransmissionOffPerResource;
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_PRSTransmissionOffIndication */
typedef struct NRPPA_PRSTransmissionOffIndication {
	NRPPA_PRSTransmissionOffIndication_PR present;
	union NRPPA_PRSTransmissionOffIndication_u {
		NULL_t	 pRSTransmissionOffPerTRP;
		struct NRPPA_PRSTransmissionOffPerResourceSet	*pRSTransmissionOffPerResourceSet;
		struct NRPPA_PRSTransmissionOffPerResource	*pRSTransmissionOffPerResource;
		struct NRPPA_ProtocolIE_Single_Container	*choice_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PRSTransmissionOffIndication_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PRSTransmissionOffIndication;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_PRSTransmissionOffIndication_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_PRSTransmissionOffIndication_1[4];
extern asn_per_constraints_t asn_PER_type_NRPPA_PRSTransmissionOffIndication_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_PRSTransmissionOffIndication_H_ */
#include <asn_internal.h>
