/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_PRSResource_QCLInfo_H_
#define	_NRPPA_PRSResource_QCLInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_PRSResource_QCLInfo_PR {
	NRPPA_PRSResource_QCLInfo_PR_NOTHING,	/* No components present */
	NRPPA_PRSResource_QCLInfo_PR_qCLSourceSSB,
	NRPPA_PRSResource_QCLInfo_PR_qCLSourcePRS,
	NRPPA_PRSResource_QCLInfo_PR_choice_Extension
} NRPPA_PRSResource_QCLInfo_PR;

/* Forward declarations */
struct NRPPA_PRSResource_QCLSourceSSB;
struct NRPPA_PRSResource_QCLSourcePRS;
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_PRSResource-QCLInfo */
typedef struct NRPPA_PRSResource_QCLInfo {
	NRPPA_PRSResource_QCLInfo_PR present;
	union NRPPA_PRSResource_QCLInfo_u {
		struct NRPPA_PRSResource_QCLSourceSSB	*qCLSourceSSB;
		struct NRPPA_PRSResource_QCLSourcePRS	*qCLSourcePRS;
		struct NRPPA_ProtocolIE_Single_Container	*choice_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PRSResource_QCLInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PRSResource_QCLInfo;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_PRSResource_QCLInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_PRSResource_QCLInfo_1[3];
extern asn_per_constraints_t asn_PER_type_NRPPA_PRSResource_QCLInfo_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_PRSResource_QCLInfo_H_ */
#include <asn_internal.h>
