/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_UE_TEG_ReportingPeriodicity_H_
#define	_NRPPA_UE_TEG_ReportingPeriodicity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_UE_TEG_ReportingPeriodicity {
	NRPPA_UE_TEG_ReportingPeriodicity_ms160	= 0,
	NRPPA_UE_TEG_ReportingPeriodicity_ms320	= 1,
	NRPPA_UE_TEG_ReportingPeriodicity_ms1280	= 2,
	NRPPA_UE_TEG_ReportingPeriodicity_ms2560	= 3,
	NRPPA_UE_TEG_ReportingPeriodicity_ms61440	= 4,
	NRPPA_UE_TEG_ReportingPeriodicity_ms81920	= 5,
	NRPPA_UE_TEG_ReportingPeriodicity_ms368640	= 6,
	NRPPA_UE_TEG_ReportingPeriodicity_ms737280	= 7
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_UE_TEG_ReportingPeriodicity;

/* NRPPA_UE-TEG-ReportingPeriodicity */
typedef long	 NRPPA_UE_TEG_ReportingPeriodicity_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPA_UE_TEG_ReportingPeriodicity_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_UE_TEG_ReportingPeriodicity;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPA_UE_TEG_ReportingPeriodicity_specs_1;
asn_struct_free_f NRPPA_UE_TEG_ReportingPeriodicity_free;
asn_struct_print_f NRPPA_UE_TEG_ReportingPeriodicity_print;
asn_constr_check_f NRPPA_UE_TEG_ReportingPeriodicity_constraint;
per_type_decoder_f NRPPA_UE_TEG_ReportingPeriodicity_decode_aper;
per_type_encoder_f NRPPA_UE_TEG_ReportingPeriodicity_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_UE_TEG_ReportingPeriodicity_H_ */
#include <asn_internal.h>
