/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-PDU-Contents"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_AperiodicSRS_H_
#define	_NRPPA_AperiodicSRS_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_AperiodicSRS__aperiodic {
	NRPPA_AperiodicSRS__aperiodic_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_NRPPA_AperiodicSRS__aperiodic;

/* Forward declarations */
struct NRPPA_SRSResourceTrigger;
struct NRPPA_ProtocolExtensionContainer;

/* NRPPA_AperiodicSRS */
typedef struct NRPPA_AperiodicSRS {
	long	 aperiodic;
	struct NRPPA_SRSResourceTrigger	*sRSResourceTrigger;	/* OPTIONAL */
	struct NRPPA_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_AperiodicSRS_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NRPPA_aperiodic_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_AperiodicSRS;
extern asn_SEQUENCE_specifics_t asn_SPC_NRPPA_AperiodicSRS_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_AperiodicSRS_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_AperiodicSRS_H_ */
#include <asn_internal.h>
