/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_PosSIBs_H_
#define	_NRPPA_PosSIBs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "NRPPA_PosSIB-Type.h"
#include "NRPPA_PosSIB-Segments.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRPPA_AssistanceInformationMetaData;
struct NRPPA_ProtocolExtensionContainer;

/* Forward definitions */
typedef struct NRPPA_PosSIBs__Member {
	NRPPA_PosSIB_Type_t	 posSIB_Type;
	NRPPA_PosSIB_Segments_t	 posSIB_Segments;
	struct NRPPA_AssistanceInformationMetaData	*assistanceInformationMetaData;	/* OPTIONAL */
	long	*broadcastPriority;	/* OPTIONAL */
	struct NRPPA_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PosSIBs__Member;

/* NRPPA_PosSIBs */
typedef struct NRPPA_PosSIBs {
	A_SEQUENCE_OF(PosSIBs__Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_PosSIBs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PosSIBs;
extern asn_SET_OF_specifics_t asn_SPC_NRPPA_PosSIBs_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_PosSIBs_1[1];
extern asn_per_constraints_t asn_PER_type_NRPPA_PosSIBs_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_PosSIBs_H_ */
#include <asn_internal.h>
