/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_PosSIB_Type_H_
#define	_NRPPA_PosSIB_Type_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_PosSIB_Type {
	NRPPA_PosSIB_Type_posSibType1_1	= 0,
	NRPPA_PosSIB_Type_posSibType1_2	= 1,
	NRPPA_PosSIB_Type_posSibType1_3	= 2,
	NRPPA_PosSIB_Type_posSibType1_4	= 3,
	NRPPA_PosSIB_Type_posSibType1_5	= 4,
	NRPPA_PosSIB_Type_posSibType1_6	= 5,
	NRPPA_PosSIB_Type_posSibType1_7	= 6,
	NRPPA_PosSIB_Type_posSibType1_8	= 7,
	NRPPA_PosSIB_Type_posSibType2_1	= 8,
	NRPPA_PosSIB_Type_posSibType2_2	= 9,
	NRPPA_PosSIB_Type_posSibType2_3	= 10,
	NRPPA_PosSIB_Type_posSibType2_4	= 11,
	NRPPA_PosSIB_Type_posSibType2_5	= 12,
	NRPPA_PosSIB_Type_posSibType2_6	= 13,
	NRPPA_PosSIB_Type_posSibType2_7	= 14,
	NRPPA_PosSIB_Type_posSibType2_8	= 15,
	NRPPA_PosSIB_Type_posSibType2_9	= 16,
	NRPPA_PosSIB_Type_posSibType2_10	= 17,
	NRPPA_PosSIB_Type_posSibType2_11	= 18,
	NRPPA_PosSIB_Type_posSibType2_12	= 19,
	NRPPA_PosSIB_Type_posSibType2_13	= 20,
	NRPPA_PosSIB_Type_posSibType2_14	= 21,
	NRPPA_PosSIB_Type_posSibType2_15	= 22,
	NRPPA_PosSIB_Type_posSibType2_16	= 23,
	NRPPA_PosSIB_Type_posSibType2_17	= 24,
	NRPPA_PosSIB_Type_posSibType2_18	= 25,
	NRPPA_PosSIB_Type_posSibType2_19	= 26,
	NRPPA_PosSIB_Type_posSibType2_20	= 27,
	NRPPA_PosSIB_Type_posSibType2_21	= 28,
	NRPPA_PosSIB_Type_posSibType2_22	= 29,
	NRPPA_PosSIB_Type_posSibType2_23	= 30,
	NRPPA_PosSIB_Type_posSibType2_24	= 31,
	NRPPA_PosSIB_Type_posSibType2_25	= 32,
	NRPPA_PosSIB_Type_posSibType3_1	= 33,
	NRPPA_PosSIB_Type_posSibType4_1	= 34,
	NRPPA_PosSIB_Type_posSibType5_1	= 35,
	NRPPA_PosSIB_Type_posSibType6_1	= 36,
	NRPPA_PosSIB_Type_posSibType6_2	= 37,
	NRPPA_PosSIB_Type_posSibType6_3	= 38,
	/*
	 * Enumeration is extensible
	 */
	NRPPA_PosSIB_Type_posSibType1_9	= 39,
	NRPPA_PosSIB_Type_posSibType1_10	= 40,
	NRPPA_PosSIB_Type_posSibType6_4	= 41,
	NRPPA_PosSIB_Type_posSibType6_5	= 42,
	NRPPA_PosSIB_Type_posSibType6_6	= 43,
	NRPPA_PosSIB_Type_posSibType1_11	= 44,
	NRPPA_PosSIB_Type_posSibType1_12	= 45,
	NRPPA_PosSIB_Type_posSibType2_17a	= 46,
	NRPPA_PosSIB_Type_posSibType2_18a	= 47,
	NRPPA_PosSIB_Type_posSibType2_20a	= 48,
	NRPPA_PosSIB_Type_posSibType2_26	= 49,
	NRPPA_PosSIB_Type_posSibType2_27	= 50,
	NRPPA_PosSIB_Type_posSibType6_7	= 51,
	NRPPA_PosSIB_Type_posSibType7_1	= 52,
	NRPPA_PosSIB_Type_posSibType7_2	= 53,
	NRPPA_PosSIB_Type_posSibType7_3	= 54,
	NRPPA_PosSIB_Type_posSibType7_4	= 55
} e_NRPPA_PosSIB_Type;

/* NRPPA_PosSIB-Type */
typedef long	 NRPPA_PosSIB_Type_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NRPPA_PosSIB_Type_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_PosSIB_Type;
extern const asn_INTEGER_specifics_t asn_SPC_NRPPA_PosSIB_Type_specs_1;
asn_struct_free_f NRPPA_PosSIB_Type_free;
asn_struct_print_f NRPPA_PosSIB_Type_print;
asn_constr_check_f NRPPA_PosSIB_Type_constraint;
per_type_decoder_f NRPPA_PosSIB_Type_decode_aper;
per_type_encoder_f NRPPA_PosSIB_Type_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_PosSIB_Type_H_ */
#include <asn_internal.h>
