/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "../support/nrppa-r19.1.0/38455-j10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_NRPPA_SSBBurstPosition_H_
#define	_NRPPA_SSBBurstPosition_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NRPPA_SSBBurstPosition_PR {
	NRPPA_SSBBurstPosition_PR_NOTHING,	/* No components present */
	NRPPA_SSBBurstPosition_PR_shortBitmap,
	NRPPA_SSBBurstPosition_PR_mediumBitmap,
	NRPPA_SSBBurstPosition_PR_longBitmap,
	NRPPA_SSBBurstPosition_PR_choice_extension
} NRPPA_SSBBurstPosition_PR;

/* Forward declarations */
struct NRPPA_ProtocolIE_Single_Container;

/* NRPPA_SSBBurstPosition */
typedef struct NRPPA_SSBBurstPosition {
	NRPPA_SSBBurstPosition_PR present;
	union NRPPA_SSBBurstPosition_u {
		BIT_STRING_t	 shortBitmap;
		BIT_STRING_t	 mediumBitmap;
		BIT_STRING_t	 longBitmap;
		struct NRPPA_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRPPA_SSBBurstPosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRPPA_SSBBurstPosition;
extern asn_CHOICE_specifics_t asn_SPC_NRPPA_SSBBurstPosition_specs_1;
extern asn_TYPE_member_t asn_MBR_NRPPA_SSBBurstPosition_1[4];
extern asn_per_constraints_t asn_PER_type_NRPPA_SSBBurstPosition_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NRPPA_SSBBurstPosition_H_ */
#include <asn_internal.h>
